### ISSUE TITLE
Support for customizable color formats

### ISSUE THREAD

**Issue by huyderman** [Monnoroch/ColorHighlighter#113]
It would be nice to be possible to add custom colour formats, possibly on a per-syntax scope. E.g. `rgba(255, 255, 255, 255);` or `buffer.set_draw_color(255, 255, 255);`.

**Comment by aleksijuvani** [comment]
Just dropping in to say that I would also find this useful. In my current project I could've used support for `{255 255 255}` and `[1 1 1]`.

**Comment by dofine** [comment]
Same here. In our project we're using a special format of hex code, eg #cFF0000, where #c indicates it's a color... Not very different from standard hex code. But don't know how to implement it.

**Comment by Monnoroch** [comment]
Lucky you! 
Now, CH does support customizable color formats. 
Check out .sublime-settings file.

**Comment by dofine** [comment]
@Monnoroch Hi I've got a question. 
We use `#cFF0000 this is colored #n` to highlight whatever inside `#cFF0000` and `#n`. Now with customized color format I can get `#cFF0000` to be colored. Any chance to highlight the content between `#cFF0000` and `#n`?

**Comment by Monnoroch** [comment]
I think you could write a regex for it, yeah.
