### ISSUE TITLE
TypeError: 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by doptrois** [Monnoroch/ColorHighlighter#133]
I'd love to use your plugin :)
Unfortunately I've got an error message in the Sublime Text 2 console:

> TypeError: 'encoding' is an invalid keyword argument for this function

Environment:
- Ubuntu 14.04.1
- Sublime Text 2.0.2, Build 2221
- Python 2.7.6
- ImageMagick (latest version)

It seems there is a problem in ColorHightlighter.py on line 40-50:

``` python
def write_file(fl, s):
    with open(fl, "w", encoding="utf8") as f:
        f.write(s)

def write_bin_file(fl, s):
    with open(fl, "wb") as f:
        f.write(s)

def read_file(fl):
    with open(fl, "r", encoding="utf8") as f:
        return f.read()
```

Any idea how to fix this?

**Comment by yuanhanchun** [comment]
delete it.
