### ISSUE TITLE
Color variable in other folder

### ISSUE THREAD

**Issue by warchieflll** [Monnoroch/ColorHighlighter#154]
Hi, I have seen if you set a variable with the color, the Color Highlighter shows that color: that's great! It also works if you set '@import colors' at the top with the variables: that's even better. But when you set '@import ../variables/colors', it coudn't handle it. Is it possible to add this feature?

**Comment by kyleknighted** [comment]
@gerbenvandijk concept is a great idea.

I work on multiple apps, and most of them there are tons of SCSS files that are all imported into one file, so they don't all have calls to import the color variables file.

Being able to define a string or array of files to pull the variables from would be great!

**Comment by Monnoroch** [comment]
Should be fixed in V7.

**Comment by qikkeronline** [comment]
:+1:

**Comment by qikkeronline** [comment]
@Monnoroch - so if I understand it well, then it is now possible to point the plugin to a _variables.scss file using the .sublime-project file? I can't seem to find any documentation or setting for this. Thanks!

**Comment by qikkeronline** [comment]
If not, then let me know and I'll open a new issue for it. Seems like a killer feature to me and some other people apparently :-)

**Comment by Monnoroch** [comment]
Nope, closed this one by mistake.
Could you please describe the feature you want in details?

**Comment by qikkeronline** [comment]
Yea sure.

So I'd love to be able to add a string to the .sublime-project file, where I can point the plugin towards a specific SCSS file containing all my color variables. We often use one file where we do all of our @import statements - and often I dont have that file open or I don't have the color variables files open - hence the hightlighting does not work anymore. I would like to be able to define on a per-project basis, hence that I am suggesting to use the .sublime-project file in stead of the plugin settings.

In my case - I'd like to be able to do something like this in my .sublime-project file:

	"color_variable_file" : "./webroot/wp-content/themes/clientname/assets/sass/variables/colors.scss"

I hope that's clear like this, if not I'm happy to clarify more.

**Comment by Monnoroch** [comment]
Awesome, thanks, this should be easy!

**Comment by qikkeronline** [comment]
Awesome, thanks! Looking forward to it :-)

**Comment by Monnoroch** [comment]
Done https://github.com/Monnoroch/ColorHighlighter/commit/2b9c5ad19b1d73c642a9c13143c24be07ec3cf9d

**Comment by qikkeronline** [comment]
Awesome, thanks! I'll start using it straight away - i'll let you know how it works.
