### ISSUE TITLE
Problems with 'Go to variable definition'

### ISSUE THREAD

**Issue by swhinnem** [Monnoroch/ColorHighlighter#160]
Overall, this plugin is so sweet. But have run into two problems with SASS colors-

1. It doesn't recognize SASS variables with a dash: e.g. the menu option is available for `$red`, but not available for `$light-red`.
2. It's not jumping to the correct variable definition. Here's a screengrab where I'm selecting 'Go to variable definition' for several colors- it's getting every one wrong:
![colors](https://cloud.githubusercontent.com/assets/1100018/4905971/ce83f55a-6454-11e4-9f93-e5cd12ba59fb.gif)

**Comment by Monnoroch** [comment]
Should be fixed in V7.
