### ISSUE TITLE
Yosemite color picker generating 8 digit hexadecimal, e.g. #47D52DFF

### ISSUE THREAD

**Issue by benwoodward** [Monnoroch/ColorHighlighter#161]
![image](https://cloud.githubusercontent.com/assets/1472981/4915953/55a345fc-64d4-11e4-9a05-ba6b52860d54.png)

![image](https://cloud.githubusercontent.com/assets/1472981/4915976/7414c1e6-64d4-11e4-8658-3c892bce7dbe.png)

Is there a way to change this?

**Comment by Monnoroch** [comment]
This is correct.
