### ISSUE TITLE
Alters copy / paste functionality in .css files

### ISSUE THREAD

**Issue by Arty2** [Monnoroch/ColorHighlighter#165]
First of all, thank you for this plugin, it really proves useful in many occasions.
There are however a few details that need some ironing. 

(using Sublime Text 3, build 3065)

In this particular example, when selecting the color value, Ctrl+C copies the whole line instead of the selection only as it should, regardless of the color value:

`color: #000;`

**Comment by Monnoroch** [comment]
Should be fixed in V7.
