### ISSUE TITLE
Color Picker doesn't load in ST3, OS X 10.9.5

### ISSUE THREAD

**Issue by designingdesign** [Monnoroch/ColorHighlighter#170]
The highlighter works, but the color picker does not, when I try to open the color picker, an exec is loaded in the dock called "ColorPicker_osx_x64"

**Comment by Monnoroch** [comment]
Can anybody build small OSX obj-c program for me, so I could fix this?

**Comment by thematthopkins** [comment]
Submitted executable to fix this in #270.  This should also resolve #215

**Comment by Monnoroch** [comment]
Fixed by #270.
