### ISSUE TITLE
Syntax specific theme gets overridden with default theme

### ISSUE THREAD

**Issue by charlesroper** [Monnoroch/ColorHighlighter#172]
I'm using the MarkdownEditing package along with the syntax-specific themes it provides. However, when I create a new file and then switch to Markdown syntax, my default theme somehow gets applied instead of the syntax-specific one. I then have to select `Preferences > Color scheme forget for view` to get the syntax-specific theme back again.

This problem appears to be directly related to something ColorHighlighter is doing. If I disable ColorHighlighter, then new files set to Markdown get assigned the correct syntax-specific theme.

**Comment by Theowningone** [comment]
This same issue causes conflicts with Sublime ToDone.

The color scheme should be: `Packages/ToDone/Monokai_todone.hidden-tmTheme`
but instead `view.settings().get('color_scheme')` returns `Packages/User/Color Highlighter/themes/Phoenix Dark Red.tmTheme`

**Comment by Monnoroch** [comment]
Should be fixed in V7.
