### ISSUE TITLE
Plugin Crash on load

### ISSUE THREAD

**Issue by Graham42** [Monnoroch/ColorHighlighter#175]
Was using search and replace and ended up opening 6 different less files full of variables. The plugin crashed and turned the background of sublime white. Error message popup was:
```
Error loading colour scheme Packages/User/Color Highlighter/themes/Monokai (SL).tmThme: 
    Error parsing plistxml: epected = in file Packages/User/Color Highlighter/themes/Monokai (SL).tmThme on line 4178
```

I restarted sublime but as soon as I click in the editing area the plugin crashes again with the same error.

I've attached a screenshot.
![subl3_color-highlight](https://cloud.githubusercontent.com/assets/2476733/5321130/677d16d0-7c86-11e4-90c1-b847c14738b8.png)

**Comment by nickdichiara** [comment]
I am having the same issue as this. ST3, OSX Yosemite 10.10.2

Even after an uninstall of ColorHighlighter it still shows this error.

**Comment by nicdichiara** [comment]
Update: 

I have uninstalled ColorHighlighter, closed out all files that had color codes, and then restarted ST. Afterwards, I was able to reinstall ColorHighlighter and it is working as normal. 


For completeness, these were the error codes I was receiving:

Error loading colour scheme Packages/User/Color Highlighter/themes/Monokai (SL).tmTheme: Error parsing plist xml: expected < in file Packages/User/Color Highlighter/themes/Monokai (SL).tmTheme on line: 1721

Error loading colour scheme Packages/User/Color Highlighter/themes/Monokai (SL).tmTheme: Error parsing plist xml: expected < in file Packages/User/Color Highlighter/themes/Monokai (SL).tmTheme on line: 1466

Error loading colour scheme Packages/User/Color Highlighter/themes/Monokai (SL).tmTheme: Error parsing plist xml: expected < in file Packages/User/Color Highlighter/themes/Monokai (SL).tmTheme on line: 684

**Comment by leslc** [comment]
FYI, tried this but still getting the error message:

"Error loading colour scheme Packages/User/Color Highlighter/themes/Monokai.tmTheme: Error parsing plist xml: unexpected end of data in file Packages/User/Color Highlighter/themes/Monokai.tmTheme on line: 1894"

(Sublime Text 3, build 3083)

**Comment by Graham42** [comment]
Sublime caches the package, so the usual reinstall using the package manager does solve the issue. 

To fix:

1. Uninstall using the package manager
1. Manually remove the folder in the user data directory
1. Reinstall 

I've found as long as I don't  open too many files at once, the plugin doesn't break.

**Comment by leslc** [comment]
Thanks @Graham42,  I uninstalled the package and cleared these two directories:
~/Library/Application Support/Sublime Text 3/Packages/User/Color Highlighter
~/Library/Application Support/Sublime Text 3/Packages/User/Color Highlighter

Unfortunately, I still run into this problem.  It's probably because there's so many variables in this file. :)  I'll try to isolate and file a separate bug report.

**Comment by Graham42** [comment]
@leslc If your problem is from too many variables, you don't need to file a separate issue. That's the underlying cause of my crashes.

**Comment by tanweijiu** [comment]
thks, i have forget to close the files that was opened ...

**Comment by Monnoroch** [comment]
Should be fixed in V7.

**Comment by leslc** [comment]
Ah, back to the goodness!  Thank you.
