### ISSUE TITLE
Color format is case sensitive

### ISSUE THREAD

**Issue by draco1023** [Monnoroch/ColorHighlighter#178]
![2014-12-10_160839](https://cloud.githubusercontent.com/assets/1821583/5372637/13b2551a-8087-11e4-9eda-ec20545ffa07.jpg)
![2014-12-10_160824](https://cloud.githubusercontent.com/assets/1821583/5372636/13adb596-8087-11e4-8379-3d362e826b46.jpg)
As shown in pictures above, ColorHighlighter does not work with the word 'Gray'. Other words with upper case won't get highlighted either.

**Comment by wesbos** [comment]
:+1: to this - many colour generators use uppercase colour names and it is part of the spec - it would be nice to have uppercase colours highlighted as well.

**Comment by wagerfield** [comment]
:+1: to this too. I like to declare colour constants using uppercase, underscore separated names when using SASS, Stylus etc.

```stylus
// constants.styl
COLOR_ORANGE = #FF9125

h1
    color COLOR_ORANGE
``` 

Introducing underscores into my variable names stops them being picked up by ColorHighlighter.

**Comment by draco1023** [comment]
Thanks
