### ISSUE TITLE
Working incredibly slow

### ISSUE THREAD

**Issue by KroniK907** [Monnoroch/ColorHighlighter#180]
I am on windows 7 running sublime text 3 (64 bit, version 3605). I am running a bare bones sublime install with only the package control package and Color Highlighter. Whenever I click on a hex color it pauses for close to 10 seconds and then correctly highlights the code. I opened the command line and tested it again and got the following errors:

```
convert error:
Invalid Parameter - TrueColorMatte

convert error:
Invalid Parameter - TrueColorMatte
```

Im not sure if this has something to do with the long delay, however it is something I noticed.

I would love to use this plugin but the 10 second delay every time I click on a Hex color code makes it way too much of a hassle.

**Comment by skube** [comment]
I'm on Win7 ST3 v3065 
I also have the delay and the error:
```
convert error:
Invalid Parameter - TrueColorMatte
```
Setting `"icons": false` in my user settings didn't help. Any other suggestions?

**Comment by fgimian** [comment]
+1 same problem here too I'm afraid

**Comment by name-k** [comment]
Just used the plugin for the first time today with latest ST3 dev version on latest Win10. The plugin slows performance down too much, that, unfortunately makes it useless. I've tried different settings listed above, which did not help. 
Is this issue actual only for Windows machines?

**Comment by Monnoroch** [comment]
The only possible slow thing -- is a whole file highlighting.
Is it still slow on your machine when you disable it?

**Comment by name-k** [comment]
If you mean `icons_all` - it is set to `false`.

**Comment by Monnoroch** [comment]
I mean ha_style: "none".

**Comment by name-k** [comment]
Yes, now lags are gone. Thanks!

**Comment by Monnoroch** [comment]
Yeah, this thing parses the whole file with a very big regex. Should be OK on modest-sised files or morend hardware though.

**Comment by GaidaiAndrii** [comment]
my user settings file is exectly this:
```json
{
"ha_style": "filled",
"icons": false,
"ha_icons": false
}
```
I first have tried only use option `"ha_style": "filled"`, but removed the whole package because of its extremely slow work.
Then I have found this page and post about `"icons": false`. It started to work faster, but still not what I expected.
Finally, I dig default settings for properties and added `"ha_icons": false`. Now I'm happy with the speed.
PS: I use Win 7 on not so fast computer.
