### ISSUE TITLE
ctrl+shift+a key conflicts with expand selection to tag

### ISSUE THREAD

**Issue by radubr** [Monnoroch/ColorHighlighter#185]
Now the ctrl+shift+a key binding in Windows/Linux for HTML files that expands selection to tag (default key in sublime) is not working because it's overwritten by this plugin.

Possible solutions: 1. notify the users about this, 2. change the key to another one but keep in mind to prevent any other conflict.

**Comment by jackw** [comment]
super+shift+a key binding also affects Mac OS. I tried adding "extensions" to my ColorHighlighter.sublime-settings file but it didn't make a difference. 

    {
    	"default_keybindings": false,
    	"extensions":
    	[
    		"scss",
    		"sass",
    		"css"
    	],
    	"style": "underlined_solid"
    }


I've had to disable the key bindings for this plugin which is really annoying given what a great addition it is to sublime text.

**Comment by Monnoroch** [comment]
Should be fixed in V7.

**Comment by captaincoo1** [comment]
I'm having this issue on Mac OS. I could not use the "Expand Selection to Tag" shortcut, command-shift-a, while this package was enabled.
