### ISSUE TITLE
Variable name are detected (i prefer not)

### ISSUE THREAD

**Issue by isyara** [Monnoroch/ColorHighlighter#188]
Hi, 
I have disabled color name in the array settings but in scss file the variables (with color name) are detected.

![capture d ecran 2015-01-20 a 11 31 12](https://cloud.githubusercontent.com/assets/2648791/5815673/ee4e7f8e-a097-11e4-8eca-c3830d6802a7.png)

**Comment by Monnoroch** [comment]
Those formats are not about highlighting, but about converting colors.

2015-01-20 13:34 GMT+03:00 isyara <notifications@github.com>:
