### ISSUE TITLE
Highlighted selection has odd/non-rounded corners

### ISSUE THREAD

**Issue by Fironet** [Monnoroch/ColorHighlighter#190]
Minor issue, but I noticed the corners of highlighted selections isn't rounded. Not sure if it relies on an image sprite that's breaking, or what is causing it. Using ST3 (build 3065) on Windows.

![1](https://cloud.githubusercontent.com/assets/6971981/5989071/cc97191a-a9ce-11e4-8f46-c71fbd9e9172.png) ![2](https://cloud.githubusercontent.com/assets/6971981/5989072/cccd02dc-a9ce-11e4-8055-2efc78a5c285.png)

**Comment by MattDMo** [comment]
You can see this to a greater or lesser extent in all three platforms - it's just how `sublime.DRAW_OUTLINED` is implemented. It doesn't specifically have anything to do with this particular plugin.

**Comment by Monnoroch** [comment]
Yes, I can't do anything with it.
