### ISSUE TITLE
Appears to conflict with MarkdownEditing color schemes

### ISSUE THREAD

**Issue by Fironet** [Monnoroch/ColorHighlighter#191]
This left me a little baffled. I have installed [MarkdownEditing](https://github.com/SublimeText-Markdown/MarkdownEditing/) which applies color schemes to open markdown files, as well as other extensions added to the settings file (in my case also .txt).

For whatever reason with Color Highlighter installed open .txt files that would normally have the MarkdownEditing theme applied were overridden by the default color scheme. After comparing preference files and restarting ST multiple times I found the only way to stop this behavior was removing Color Highlighter.

I could reproduce this again by re-installing the package, where upon successful installation all open MarkdownEditing-affected files were changed to the default color scheme, even though such extensions are not included in the Color Highlighter settings.

**Comment by Monnoroch** [comment]
Could you please check if it's fixed in a latest version?

**Comment by Fironet** [comment]
> Could you please check if it's fixed in a latest version?

Seems to be fixed in the latest version, cheers. Closing the issue.
