### ISSUE TITLE
Sass/SCSS variable definitions not showing associated color

### ISSUE THREAD

**Issue by kyleknighted** [Monnoroch/ColorHighlighter#193]
On my variable definition screen, the colors are shown in the sidebar as expected. But, it doesn't work on the variables throughout the rest of my app.

Is there a way to set ColorHighlighter to use an array of specific variable files?

![screenshot 2015-02-05 15 05 07](https://cloud.githubusercontent.com/assets/122591/6069375/67d583b2-ad49-11e4-9531-1f445ea04744.png)

![screenshot 2015-02-05 15 04 15](https://cloud.githubusercontent.com/assets/122591/6069376/6a78bbac-ad49-11e4-9e8a-76294552640c.png)
 
I know the images don't show the exact same variables, but they're all in there.

OSX: 10.10.2
ST3: Dev Channel 3069

**Comment by Monnoroch** [comment]
https://github.com/Monnoroch/ColorHighlighter/issues/154
