### ISSUE TITLE
Plugin shows grey color

### ISSUE THREAD

**Issue by iHedgehog** [Monnoroch/ColorHighlighter#195]
ST3 OSX Yosemite 10.10.2
After I change the color in code it gets grey. But if I restart ST plugin shows colors until I change color.
![screen shot 2015-02-12 at 12 40 46](https://cloud.githubusercontent.com/assets/6762673/6164906/842b233a-b2b4-11e4-9b80-2ea7b3768a54.png)

**Comment by Monnoroch** [comment]
Should be fixed in V7.
