### ISSUE TITLE
Confused about `style`and `ha_style` settings

### ISSUE THREAD

**Issue by skube** [Monnoroch/ColorHighlighter#196]
I'm confused about the differences between `style` and `ha_style`:

    "style": "default",
    "ha_style": "filled",

`ha_style` has the following options:
- "none"
- "filled"
- "outlined"
- "underlined_solid"
- "underlined_strippled"
- "underlined_squiggly"

What are the options for `style` and what's the difference between the two?

**Comment by Monnoroch** [comment]
style is for usual highlighting, and ha_style is for whole file highlighting.

**Comment by skube** [comment]
What are the value options for `style`?

**Comment by Monnoroch** [comment]
Same as ha_style.

**Comment by skube** [comment]
It doesn't not appear to work properly for me. I have the following set:
```
"style": "outlined",
"ha_style": "none"
```
But when the cursor is on a color, the style is filled (default) and not outlined.
