### ISSUE TITLE
The color picker does not show on st3 with elementary freya 

### ISSUE THREAD

**Issue by PerfectCarl** [Monnoroch/ColorHighlighter#197]
Elementary freya uses ubuntu 14.04 as a base and gtk 3.14

When I right click on a color in my less file, the color picker is not displayed.
Is it something that I should do?

**Comment by LOQUILLO** [comment]
Hi @PerfectCarl use FindKeyConflict for to know ctrl-shift-c conflicts, or just put the cursor (or multiple cursors) on the color code and select "Choose color" in context menú (in Windows right click mouse). Select the color in a popup color picker and all color codes under your cursors will change.

**Comment by imanrp** [comment]
Hi @PerfectCarl , I use Freya too. Installing qt5 library solves this.

sudo apt-get install libqt5widgets5

**Comment by Monnoroch** [comment]
Should be fixed in V7.
