### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by hemu1** [Monnoroch/ColorHighlighter#199]
Love the feature, very useful for css work. However, I experience a lag of about half a second when I click the color text, even with all features other than the underline off. When I disable color highlighter, everything works smoothly. It's very annoying, especially if I want to double click the color. Any tips are appreciated!

**Comment by hemu1** [comment]
Found the culprit. For anyone experiencing a similar lag issue, set the following in user settings:
"icons": false
Now everything else works silky smooth.

**Comment by Monnoroch** [comment]
It seems, that convert ilagemagic utility works slow for you. Not sure, why.

**Comment by hemu1** [comment]
I do have several other plugins using the gutter icons, such as the bracket highlighter. Maybe the interaction of changing the icon and back again had something to do with it.

**Comment by Wicked0ne** [comment]
Oh man. This issue has been driving me mad lately, but I really enjoy having the color show up.

@hemu1 Very good catch. I just tried "icons: false" and it fixed the issue.

To anyone else coming here when he says "user settings" he means preferences -> package settings -> color highlighter -> user pref
