### ISSUE TITLE
Slow tab switching when importing bootstrap.less (Twitter Bootstrap)

### ISSUE THREAD

**Issue by TamasBarta** [Monnoroch/ColorHighlighter#200]
If I say `@import 'bootstrap.less';` in my project, selecting that tab introduces a significant lag, and Sublime hangs. Happens only with this plugin.

**Comment by Monnoroch** [comment]
What did you expect? The plugin has to parse a huge file, as it doesn't know, whether you need color variables in it. 
Use .css file, they don't get parsed.

**Comment by TamasBarta** [comment]
Don't take it as a judgement on your product, but others, like SublimeCodeIntel use an index, that only refreshes when you modify the files. This feature would eliminate all the lag from your plugin as well.

I accept, if you say you don't want to implement it, because whatever (you don't have time, you don't mind, you can't etc.), but your comment, and that you closed the issue communicates you thought it cannot be accomplished. Please reopen, if you don't have reasons not to fix it, so if someone else finds this issue, who can implement it, we might get instant tab switching with all the variable highlighting awesomeness.

A correctly maintained index would also enable you to highlight variables from files not opened in another tab, and not included in the currently edited file.

**Comment by Monnoroch** [comment]
Well, indexing is a good idea, and I didn't do it only because had no time yet. 
This is an open project, I always glad to accept a pull request! ;)
