### ISSUE TITLE
Doesn't support ImageMagick path with spaces

### ISSUE THREAD

**Issue by gollyzila** [Monnoroch/ColorHighlighter#201]
This is the path I'm inputting for ImageMagick:
`"convert_util_path" : "E:\\Portable Programs\\ImageMagick\\convert.exe"`

And the console outputs this:
```
convert error:
'E:\Portable' is not recognized as an internal or external command, operable program or batch file.

convert error:
'E:\Portable' is not recognized as an internal or external command, operable program or batch file.

convert error:
'E:\Portable' is not recognized as an internal or external command, operable program or batch file.

convert error:
'E:\Portable' is not recognized as an internal or external command, operable program or batch file.
```

Oh and both Sublime and ImageMagick are installed as portable apps on a flashdrive.

_Windows 7
Sublime Text 3 Stable Build 3065
ImageMagick portable: ImageMagick-6.9.0-9-Q16-x86-windows.zip_

**Comment by Monnoroch** [comment]
You have to escape spaces, I think.
3 марта 2015 г. 22:45 пользователь "gollyzila" <notifications@github.com>
написал:

**Comment by gollyzila** [comment]
Escaping with `\ ` doesn't work but `^ ` works perfectly.

`"convert_util_path" : "E:\\Portable^ Programs\\ImageMagick\\convert.exe"`
