### ISSUE TITLE
Weird behavior with SASS variables

### ISSUE THREAD

**Issue by sylver4** [Monnoroch/ColorHighlighter#203]
Hi,
I get a strange behavior on SASS variables. They are highlighted but not with the right color:
![capture d ecran 2015-03-11 a 10 08 37](https://cloud.githubusercontent.com/assets/4918968/6593225/e9438a82-c7d6-11e4-9ecf-c3d11f2c2673.png)
And if I use the same variables in an external file, they are not highlighted at all, and I can't "Go to the variable definition" (it's disabled).

**Comment by gin93r** [comment]
I'm running into the same issue. Also - every color/variable has an outline of either pinkish or greenish; can I get rid of it? ST2

**Comment by dsl2407** [comment]
Hi! There is same thing. ST3 on Ubuntu. As I discovered, bug happens only when variable takes hex value of 6 characters. Besides that, variable color depends on first three characters, fourth is something like alpha, and the last couple don't affect on it at all.
![Screenshot](https://i.imgur.com/bdMmjCe.png)

**Comment by Monnoroch** [comment]
Should be fixed in V7.
