### ISSUE TITLE
HEX color not highlighted, but RGB version of same color is...

### ISSUE THREAD

**Issue by gitnitdone** [Monnoroch/ColorHighlighter#204]
In the following list of color codes, all colors are hightlighted properly EXCEPT the last one #808080.

Note: I've just noticed that if I add a new line after the last color code it gets properly highlighted, but if I remove the new line the color is no longer hightlighted.

/***  color list  ***/
light-blue: 
	rgb(213, 245, 255)
	#D5F5FF
med-blue:
	rgb(81, 174, 200)
	#51AEC8
light-tan:
	rgb(255, 234, 212)
	#FFEAD4
med-tan:
	rgb(224, 187, 148)
	#E0BB94
logo-orange:
	rgb(241, 87, 34)
	#F15722
full-black:
	rgb(0, 0, 0)
	#000000
full-white:
	rgb(255, 255, 255)
	#FFFFFF
light-gray:
	rgb(230, 230, 230)
	#E6E6E6
med-gray:
	rgb(179, 179, 179)
	#B3B3B3
dark-gray:
	rgb(128, 128, 128)
	#808080

**Comment by Monnoroch** [comment]
Should be fixed in brand new V7.
