### ISSUE TITLE
Slows down Sublime Text 3 on scss files

### ISSUE THREAD

**Issue by numediaweb** [Monnoroch/ColorHighlighter#205]
I spent  hours trying to figure out why ST3 hangs (becomes unresponsive for 6 seconds or so) when opening `scss` files; after disabling all the plugins and installing them one by one, I finally found the culprit; `Color Highlighter.sublime-package`

It used to work without any problem but maybe recent update screwed the sass part :(

**Comment by jodzeee** [comment]
I just upgraded from ST2 to ST3 and have the same issue with CSS. My PC goes into high gear when using it. I suspect there's some conflict with my Norton Antivirus.

**Comment by numediaweb** [comment]
I don't think it has to do with Norton antivirus as I don't have it in my install but still hangs..

**Comment by WoodyWoodsta** [comment]
Having the same issue too. Even with it's own Default .sublime-settings file.

**Comment by Monnoroch** [comment]
Should be fixed in brand new V7.
