### ISSUE TITLE
Black renders with a white backing.

### ISSUE THREAD

**Issue by scotmatson** [Monnoroch/ColorHighlighter#208]
Have tried with:
  black
  #000
  rgb(0, 0, 0)

All variations of the color black have black text with a white background. The inverse should be applied, white text with a black background.

This is in Sublime Text 3 and occurs in Windows 7 and Arch Linux.

**Comment by ob7** [comment]
Thats so you can see that its highlighted.

**Comment by Monnoroch** [comment]
Should be fixed in brand new V7.
