### ISSUE TITLE
Question: Can I disable color highlighting inside css comments?

### ISSUE THREAD

**Issue by gitnitdone** [Monnoroch/ColorHighlighter#209]
I'm looking for a method of disabling the highlight feature inside css comments (single line, or block). Is this doable with the plugin as it is?

**Comment by Monnoroch** [comment]
Nope. Would need to parse whole css.
27 марта 2015 г. 0:02 пользователь "gitnitdone" <notifications@github.com>
написал:

**Comment by gitnitdone** [comment]
Damn. ok, thanks!
