### ISSUE TITLE
Feature request: text colour option

### ISSUE THREAD

**Issue by nickautomatic** [Monnoroch/ColorHighlighter#212]
Hi. Just a quick feature request / suggestion. I love ColorHighlighter, but what would be really great would be a "textcolor" option - so the colour is used as the colour of the text itself (eg. #f00 would appear in red text). For me, the underline is a little too subtle, but the block text is a little too intrusive, so that would be great. Excuse me if this is the wrong place for feature requests!

**Comment by Monnoroch** [comment]
Nice suggestion!
I'll try to figure something out, if i can find the time.

**Comment by nickautomatic** [comment]
Great, thanks!
Look forward to it, when you find the time!

**Comment by byaka** [comment]
follow request, it will be very useful.

**Comment by Monnoroch** [comment]
Check it out @ https://github.com/Monnoroch/ColorHighlighter/commit/25829f3cdff902456fb0fd5e11769fc104470e22

**Comment by byaka** [comment]
RED for background it's so agressive.. My eyes...
But it works!
