### ISSUE TITLE
Color Picker does not properly close executable [Mac, ST3]

### ISSUE THREAD

**Issue by seanjohnson08** [Monnoroch/ColorHighlighter#215]
When clicking the "Close" button (red button on top of left window), the ColorPicker_osx_x64 does not properly close. I have to force quit it in order to make it go away.

**Comment by kaishin** [comment]
Same here.

**Comment by Monnoroch** [comment]
Sorry, don't have a mac to test or even just rebuild it.

**Comment by seanjohnson08** [comment]
@Monnoroch What do you think about offloading the responsibility for popping up a color picker to http://weslly.github.io/ColorPicker/ ? It looks like there's a public API for calling the plugin from other plugins: https://github.com/weslly/ColorPicker#calling-from-other-plugins

**Comment by bobrocke** [comment]
I'd like to see a cleaner solution as well.

**Comment by carloschneider** [comment]
+1

**Comment by Monnoroch** [comment]
Dublicate https://github.com/Monnoroch/ColorHighlighter/issues/215

**Comment by seanjohnson08** [comment]
@Monnoroch you closed this issue as a duplicate of itself

**Comment by Monnoroch** [comment]
Oops!

**Comment by Monnoroch** [comment]
Duplicate https://github.com/Monnoroch/ColorHighlighter/issues/170
