### ISSUE TITLE
Conflicts with clorcoder

### ISSUE THREAD

**Issue by rocketinventor** [Monnoroch/ColorHighlighter#218]
I really like to use color coder _and_ colorhighlighter but, they quickly start to conflict with each other by creating a gazillion themes and then themes like "Packages/Brackets Color Scheme/material-dark (Colorcoded) (Colorcoded) (Colorcoded) (Colorcoded).tmTheme" or similar nonsense when I try and switch themes or something like that.
This could probably be remedied by some integration into colorcoder or at least detecting colorcoder themes and not overwriting them endlessly.

**Comment by Monnoroch** [comment]
I think there is no way to mix the tho of them, except for disabling one of the plugins or me stealing colorcoders code into CH, and I am not going to do the latter.

**Comment by rocketinventor** [comment]
Actually, monitoring the changing of themes more carefully could help.
Also, a "disable/enable colorhighighter on this view" could help.
Is it really impossible to do a proper handoff if their is some code coordination between the two repositories?
I wish sublime had a better api for this.
