### ISSUE TITLE
Variable highlighting doesn't work, even in-file

### ISSUE THREAD

**Issue by chilblane** [Monnoroch/ColorHighlighter#220]
I've been using stylus variables in my project that unfortunately are not getting highlighted, even within the definition themselves. 

![screen shot 2015-05-05 at 1 04 23 pm](https://cloud.githubusercontent.com/assets/1987274/7481766/6ca9fe94-f327-11e4-94ce-86dc32b1fbb5.png)

I'm using Sublime Text 3 3083 on OS X 10.10.3, with the following other plugins: Package Control, Stylus, Handlebars, EditorConfig, and am using ColorHighlighter's Twilight theme. I've tried switching themes and uninstalling/installing plugins with no avail.

**Comment by woble** [comment]
Same here only on Windows 7. ST3 Build 3085. Not sure if a couple of previous versions were affected.

**Comment by Monnoroch** [comment]
Should be fixed in brand new V7.
