### ISSUE TITLE
Error while using Theme - Fox

### ISSUE THREAD

**Issue by wiratamadc** [Monnoroch/ColorHighlighter#221]
I got this error a since a while ago when, didn't know what cause it. Tested using two themes (Fox theme and Solarized). Here are the error message:

```
error loading colour scheme Packages/User/Color Highlighter/themes/fox.dark.tmTheme: Expected element key
```

System is Mac OS 10.10.3 - Sublime Text 3 Build 3083

**Comment by Monnoroch** [comment]
Should be fixed in brand new V7.
