### ISSUE TITLE
User settings not picked up 

### ISSUE THREAD

**Issue by nilsborchers** [Monnoroch/ColorHighlighter#222]
Hey guys, not sure what I'm doing wrong but I checked the docs and would love to set 
```json
{
  "style": "Filled"
}
```
But it seems like everything I put in the colorhighlighter user settings is just ignored .. Anyone else facing this? Thanks!

**Comment by alundiak** [comment]
Are u able to open Default settings for plugin? Coz I am not, I have empty fil. But in fact file has content. ST3 just can't read it for some reason. 
If so, @Monnoroch should I open separate issue?

**Comment by nilsborchers** [comment]
Jup I can see the defaults 

sent from mobile

**Comment by Monnoroch** [comment]
Try "style": "filled".
