### ISSUE TITLE
Detect other hexadecimal format: 0xFFFFFF

### ISSUE THREAD

**Issue by NicolasRannou** [Monnoroch/ColorHighlighter#223]
In THREEJS, we define the color using 0xFFFFFF syntax.

Colorhighlighter doesn't detect it.

Should I just submit a pull request?

```
var boxMaterial = new THREE.MeshBasicMaterial({
        wireframe: true,
        color: 0x61F2F3
    });
```

**Comment by mahadi** [comment]
I would also like this feature as we are using the hexadecimal format in python

**Comment by Monnoroch** [comment]
Implemented in brand new V7.
