### ISSUE TITLE
ColorHighlighter vs "Color Highlighter"

### ISSUE THREAD

**Issue by alundiak** [Monnoroch/ColorHighlighter#224]
When I cloned by git like
```
$ cd .....Packages
$ git clone https://github.com/Monnoroch/ColorHighlighter.git
```
I have plugin folder with no spaces - "ColorHighlighter"

As result, when I open Default settings or keymap for plugin I have empty file.
But in fact file exists and has content. ST3 just can't find it to read.

When I try to save file (which is wrong indeed, but ...) it tells me : 

```
Unable to save ~/Library/Application Support/Sublime Text 3/Packages/Color Highlighter/ColorHighlighter.sublime-settings
Error: No such file or directory
```
Indeed, there is no such valid path.

I looked tp "py" script and saw hardcoded plugin name/foldername:

```
data_path = "Packages/User/Color Highlighter/"
```
OS:  MacOS 10.10.3.

Yeah, there is solution:
```
git clone https://github.com/Monnoroch/ColorHighlighter.git "Color Highlighter"
```
But personally I don't like spaces, so plugin folder name the same as repository name for me is ideal way.

@Monnoroch can it be fixed somehow?

**Comment by andytruett** [comment]
@alundiak You could change the hardcoded data_path in ColorHighlighter.py to not include a space and submit a pull request :)

**Comment by Monnoroch** [comment]
Use package control. Or just rename the folder manually.
