### ISSUE TITLE
Exclude Folder Paths for Go To Definition

### ISSUE THREAD

**Issue by StuartMorris0** [Monnoroch/ColorHighlighter#225]
Is there anyway to exclude folder paths for when using the gotodefintion function from a LESS file.

We have a node_modules folder for example where some results are returned in gotodefinition but should not be, is there a way to exclude that folder from the lookup?

**Comment by Monnoroch** [comment]
What for? Do not understand the problem.

**Comment by StuartMorris0** [comment]
Think this was created on the incorrect repo. Apologies
