### ISSUE TITLE
convert error: /bin/sh: convert: command not found

### ISSUE THREAD

**Issue by kilianc** [Monnoroch/ColorHighlighter#226]
On OSX

**Comment by Monnoroch** [comment]
You have to install imagemagick.
29 мая 2015 г. 0:05 пользователь "Kilian Ciuffolo" <notifications@github.com>
написал:

**Comment by kilianc** [comment]
I did from brew and it can't figure out the path, I used the abs path in config

**Comment by Monnoroch** [comment]
Sorry, can't help you with OSX, don't have one. But there were similar issues, there might be the answer.

**Comment by adambullmer** [comment]
what's the output of `brew doctor`?
