### ISSUE TITLE
Its highlighting CSS class names....

### ISSUE THREAD

**Issue by MiChAeLoKGB** [Monnoroch/ColorHighlighter#229]
Basically I have multiple color schemes and in CSS it looks like this:

    .button{
    	/* Basic styling */
    }
    .button.blue{
    	/* Different colors */
    }
    .button.pink{
    	/* Different colors */
    }

Whats happening is, that your plugin is highlighting .blue and .pink with respective colors. I think class names and IDs should be ignored. So if there is #pink or .pink it should be ignored.

![image](https://cloud.githubusercontent.com/assets/6197503/8233009/0df5013a-15d4-11e5-9e34-fa302b324537.png)

**Comment by Monnoroch** [comment]
Sould be fixed in brand new V7.
