### ISSUE TITLE
How to make color picker work on Arch Linux

### ISSUE THREAD

**Issue by ob7** [Monnoroch/ColorHighlighter#230]
For those of you using Arch Linux, this is what I needed to do to the color picker to work:
pacman -S qt5-base
pacman -S libxkbcommon-x11

The first is qt5 framework which author tells you need if your on linux.  The second is the xcb plugin necessary to start the color picker.

**Comment by Monnoroch** [comment]
Sorry, I have provided the sourcecode. You should be able to solve it for you yourself. You can handle arch, therefore you can handle 30 lines of C++ and deps.
