### ISSUE TITLE
Converting to HEX with super+shift+a

### ISSUE THREAD

**Issue by guanche** [Monnoroch/ColorHighlighter#231]
Converting back to HEX doesn't work for me. The options hsl, hsv, rgb and rgba work as expected, but the value hex, hexadecimal or #, yield no effect (value stays the same).
Working currently on OSX Yosemite with SublimeText 3.

**Comment by mahadi** [comment]
Same for me

**Comment by Monnoroch** [comment]
Sould be fixed in brand new V7.
