### ISSUE TITLE
Go to variable definition does not show up in the contextual menu

### ISSUE THREAD

**Issue by bobrocke** [Monnoroch/ColorHighlighter#236]
Mac OS, Sublime Text v3 3095

**Comment by Monnoroch** [comment]
Should be fixed in brand new V7.
Reopen, if not (I don't have macs).

**Comment by bobrocke** [comment]
It does show now, but it doesn't do anything. At least not in my .scss file.

**Comment by Monnoroch** [comment]
Could you provide the minimal example to test this? I can't reproduce the bug myself.
