### ISSUE TITLE
Colour names in variables are recognized separately

### ISSUE THREAD

**Issue by woble** [Monnoroch/ColorHighlighter#241]
As shown in the image, 'orange' is underlined with a different colour. Most recent update.

![colors](http://i.imgur.com/jkYH6hM.png)

**Comment by Monnoroch** [comment]
Yeah, I know, working on it already.

**Comment by Monnoroch** [comment]
Should be fixed https://github.com/Monnoroch/ColorHighlighter/commit/d3a4555410133e27bc67d92cec81399577b2984b.
