### ISSUE TITLE
Freezes when plugin enabled

### ISSUE THREAD

**Issue by byaka** [Monnoroch/ColorHighlighter#243]
Извеняюсь, напишу на русском.
Когда плагин включен, JS и CSS файлы фризятся при каждом нажатии клавиши (редактировании файлов) на ~секунду. При этом PYTHON'овские файлы с цветами такой проблеме не подвержены.
В консоли чисто.
Подобное поведение у меня возникало, когда в SublimeLinter я включил проверку при изменении файлов. Аналогично с питоновыми все нормально, яваскрипт фризится. Проблему решить так и не удалось, пришлось отключить проверку для js файлов.

Сам плагин обновил до последнего коммита в мастере. С v7 веткой тоже самое было.

**Comment by Monnoroch** [comment]
Быть может, это не этот плагин?
Код, выполняющийся по изменению файла тут очень небольшой.
А вообще, попробуй ST3, там должно быть значительно лучше.
Когда до ST2 доберусь -- посмотрю, но пока воспроизвести тормоза не могу.

**Comment by byaka** [comment]
никак не могу отловить условия, при которых это происходит.
проблема проявляется не сразу, через определенное (всегда разное) время (или количество действий над файлом). Но ВСЕГДА пропадает, как только в userSettings выставляю {"enabled": false}.

**Comment by Monnoroch** [comment]
Попробуй новую версию, я ее сильно оттестировал на ST2 и проблем не заметил. Если они все-таки будут, возможно, у тебя плохой диск (или сетевая FS?) и я ничем помочь не могу, кроме совета выключить "Highlight all".

**Comment by byaka** [comment]
I try latest version and no this bug happened. Thx!
