### ISSUE TITLE
Color Highlighter kills color theme for other packages

### ISSUE THREAD

**Issue by Chris-May** [Monnoroch/ColorHighlighter#244]
It seems Color Highlighter updated today in Sublime Text 3, and has killed the [PlainTasks](https://github.com/aziz/PlainTasks) color scheme.

I've disabled Color Highlighter, and the theme returns to its former self.

**Comment by Monnoroch** [comment]
It doesn't kill anything. The first law of robotics is against killing stuff. 
Please, explain your problem in detail, so I can fix it.

**Comment by Monnoroch** [comment]
I think it's about https://github.com/Monnoroch/ColorHighlighter/issues/249.

**Comment by Chris-May** [comment]
Sorry for the delay in getting back to you, and I'm also sorry for the vague bug report. I was trying to get things done on Friday, and I didn't have time to figure out what more to say.

Having said that, the linked issue doesn't sound related to me.

The experience for my coworkers and I have is that Color Highlighter is interfering with other package themes. We use PlainTask, and its default theme looks like this:
![screen shot 2015-08-24 at 9 31 17 am](https://cloud.githubusercontent.com/assets/1377336/9441300/4a79d394-4a43-11e5-9619-96699aaed4a1.png)

Friday morning, it appears Sublime updated Color Highlighter, and as a result, PlainTask looks like this:
![screen shot 2015-08-24 at 9 14 05 am](https://cloud.githubusercontent.com/assets/1377336/9441319/6d81a4a2-4a43-11e5-9872-cea878b04f67.png)

I believe Color Highlighter is the package that is interfering with PlainTasks, since its update hit at the time frame PlainTask's theme stopped working, and when I disable Color Highlighter, PlainTask's theme comes back.

**Comment by Monnoroch** [comment]
Yes, the thing is, that CH thinsk that there only is one color scheme at a time: from Preferences.sublime-settings. PlainTasks sets another theme, specific to the PlainTasks view, but CH doesn't know about it.
So, the linked issue seems to cover your problem: once I can make CH understand multiple color schemes at a time (at most one per view, though :), your problem should also be fixed.

**Comment by Monnoroch** [comment]
That said, I'm actually kinda against PlainTasks's approach. I would really like to use it with my default dark color scheme.

**Comment by Chris-May** [comment]
Ah! I see. 
Thanks for looking into that.
I hear you. There are things I like about the various Plain Tasks theme, but yeah.

**Comment by ronilaukkarinen** [comment]
Yeah, this needs improvement. Just noticed the same.
