### ISSUE TITLE
Support for view-specific Colour schemes

### ISSUE THREAD

**Issue by pradyunsg** [Monnoroch/ColorHighlighter#249]
Context: When I'm editing a colour-scheme, I would like to have ColorHighlighter enabled everywhere except for one view where I set the colour_scheme as the one which I am editing.

It's likely I'm might have missed something, but is it possible to disable ColorHighlighter on a per-view basis, probably through a view-setting? If not, consider this a feature-request.

**Comment by Monnoroch** [comment]
Could you explain, why would you want that?

**Comment by pradyunsg** [comment]
So, the workflow I follow is I have a color scheme applied on the entire editor (Preferences.sublime-settings). Then I open a single view (let's call it the "preview view") and change the color scheme of it to the one I will be editing. This way, I keep the syntax highlighting for the files I'm editing while still being able to see how the change looks in the "preview view".

With ColorHighlighter, I can apply a different color-scheme to the "preview view" but it overrides the "color_scheme" setting once I shift focus on to the "preview view". So, I'm looking for some way such that ColorHighlighter is disabled for that view. Or so that it updates it's color scheme every time I switch to the "preview view".

**Comment by Monnoroch** [comment]
Okay, thanks, first I should support per-view color schemes at all. Right now, they don't work (get overriden with global one + CH additions).

**Comment by pradyunsg** [comment]
Yeah, that's a much more concise way of putting what I said.. :stuck_out_tongue_closed_eyes: I'm supposed to be sleeping anyway.

**Comment by ashleynolan** [comment]
+1 on this issue – I use different themes for different syntaxes and I’ve had to turn off Color Highlighter temporarily because it has overridden my syntax specific settings in favour of using the global theme across all syntaxes.

**Comment by Monnoroch** [comment]
Anybody interested, could you please test my implementation from branch v7.2 of this repo?

**Comment by pradyunsg** [comment]
Me! :hand:

**Comment by pradyunsg** [comment]
While I've not been very extensive in the testing, it seems to be working well to me..

**Comment by pradyunsg** [comment]
PS: Why not automate the testing? https://github.com/twolfson/sublime-plugin-tests
