### ISSUE TITLE
CSS property names containing names of colours are parsed

### ISSUE THREAD

**Issue by woble** [Monnoroch/ColorHighlighter#251]
Shouldn't property names be ignored?

![](http://i.imgur.com/TpVVp3U.png)

**Comment by Monnoroch** [comment]
Yeah, they should!
What regex would you suggest?

**Comment by woble** [comment]
I'm not a progammer, so I honestly wouldn't know. But perhaps ignore by scope: support.type.property-name.css?

**Comment by alextegelid** [comment]
One thing to note about this is that while it does underline the words it doesn't highlight them when the cursor is over them. Can you confirm this @woble, or am I the only one seeing this?

Are there different rules for which words are underlined and which is highlighted?

**Comment by Monnoroch** [comment]
@alextegelid Yes, that is because those two work a bit differently.

**Comment by alextegelid** [comment]
Could the rules from the highlighting be applied to the underlining somehow?

**Comment by alextegelid** [comment]
Or rather, could those rules be used all over?

**Comment by yisibl** [comment]
+1

**Comment by Romainpetit** [comment]
+1 I cannot use the plugin until this is not fixed. I have many colours words in my selectors names.
It highlights words that are not colours using colors that are not in my colour set.

**Comment by Monnoroch** [comment]
Well, you could look into plugins settings.

**Comment by wheublein** [comment]
It would be nice to have a setting to turn off all parsing of color words in the text and leave the highlighting on otherwise. I haven't done much Python coding, but a quick hack to turn off color words is to add 'names_to_hex = {}' at the bottom of the colors.py file. This sets the lookup dictionary for color words to empty.

**Comment by wheublein** [comment]
The option to disable all word-to-color highlighting while keeping the rest of the highlighting active would be nice. This is a quick hack, but I was able to disable all word-to-color highlighting by adding the following at the bottom of the colors.py file:

>`names_to_hex = {
>    'navajowhite': '#FFDEADFF',
>    }`

If I get some time I will try to find a way to get the same result in a way that integrates better with the existing code and settings.

**Comment by wheublein** [comment]
Another minor and related issue - HTML Entities of the format `&#entity_number;` should also probably be ignored.

**Comment by Romainpetit** [comment]
Exactly. What is missing is the option to **exclude** one format only. 
I cleared the array of colors in colors.py, it also does the job.

**Comment by Monnoroch** [comment]
Excluding one format only can be made by just deleting it from settings.
If this is not the case, then this is a bug, and a topic for different issue.

**Comment by wheublein** [comment]
Deleting the @named from settings does not disable the highlighting of color-words. I have opened a new Issue to cover this.

**Comment by Monnoroch** [comment]
Okay, I'll dig into it as soon as I have a free day, thanks!
