### ISSUE TITLE
#xxx shouldn't highlight if directly followed by non-hex

### ISSUE THREAD

**Issue by mreinhardt** [Monnoroch/ColorHighlighter#253]
Here's an example:

![screen shot 2015-08-25 at 11 10 18 am](https://cloud.githubusercontent.com/assets/582461/9475221/34841e46-4b1a-11e5-8621-964b143cba34.png)

The `#add` in `#addModal` shouldn't be highlighted. Perhaps change the regex somehow with a negative lookahead?

**Comment by Monnoroch** [comment]
Duplicates https://github.com/Monnoroch/ColorHighlighter/issues/252
