### ISSUE TITLE
Very bad performance when hilighting color under cursor

### ISSUE THREAD

**Issue by shinmai** [Monnoroch/ColorHighlighter#254]
Windows 10, 64-bit ST3 3083. Hilighting any color code will freeze Sublime Text for 5-10 seconds.

The log will display:
```
convert error:
Invalid Parameter - TrueColorMatte
```
whenever this happens.

The same error is in the log when opening a while and ColorHilighter is generating the underlines and this process also takes a long while, but with the underlines, this doesn't block the UI unlike with the hilights. After the error has happened once, SublimeText also stops syntax hilighting until it's restarted.

**Comment by Monnoroch** [comment]
Disable showing icons. Your ImageMagick seems to not work.

**Comment by shinmai** [comment]
Oh, I already had icons disabled, because I don't have ImageMagick installed, and the README said it's needed for gutter icons.

I didn't make the connection with "convert" in the error and ImageMagick until you mentioned it. The script definitely seems to try and execute convert even when icons are disabled (and on a windows system with no ImageMagick in PATH, "convert" is a built-in command to convert a FAT filesystem to NTFS, which would explain the invalid parameter, certainly).

**Comment by evandrocoan** [comment]
For reference, this is was my full error output.
```
CONVERT CALL:
convert -type TrueColorMatte -channel RGBA -size 32x32 -alpha transparent xc:none -fill "#808080FF" -draw "circle 15,16 8,10" png32:"D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\User\Color Highlighter\icons\808080FF"
convert error:
Invalid Parameter - TrueColorMatte


CONVERT CALL:
convert -type TrueColorMatte -channel RGBA -size 32x32 -alpha transparent xc:none -fill "#808080FF" -draw "circle 15,16 8,10" png32:"D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\User\Color Highlighter\icons\808080FF"
convert error:
Invalid Parameter - TrueColorMatte
```
