### ISSUE TITLE
Rename Plugin to be consistent everywhere

### ISSUE THREAD

**Issue by pradyunsg** [Monnoroch/ColorHighlighter#260]
Currently, the plugin has 2 names: "Color Highlighter" and "ColorHighlighter".

"Color Highlighter" is used is in Package Control and the access-to-package-files code.
"ColorHighlighter" is used in the naming of the files as well as this repository.

For consistency, it makes sense to make the name either "Color Highlighter" or "ColorHighlighter". This, of course, depends on whether it's even worth the effort but I just wanted to float the idea...

**Comment by Monnoroch** [comment]
I don't like filenemas with spaces, but package control name should definitely be with a space. 
So what do I do? And how do I make it backwards compatible? And is it worth it?

**Comment by pradyunsg** [comment]
Changing the file names to add spaces seems to be a good idea to me as I would not like to mess too much with the name in Package Control.

As for backwards compatibility, I suggest checking for both "ColorHighlighter.sublime-settings" and "Color Highlighter.sublime-settings" for the time-being, deprecating the former, possibly with a prompt to rename every 10th or so plugin-loaded about it.

As for whether it's worth it, I'm not really sure. It's more of it's better to be consistent and it should all work fine if the deprecation is handled well... I think it's more of a decision for you to take.

**Comment by pradyunsg** [comment]
And possibly while we're at it, the settings could be renamed to more sensible ones.

Another Idea: Automatically try to generate a "Color Highlighter.sublime-settings" for the user on first run in the deprecation period using their customized settings and notify them about the change.

**Comment by Monnoroch** [comment]
> Changing the file names to add spaces
Nope. Will not do. Ever.

> Automatically try to generate a "Color Highlighter.sublime-settings" for the user on first run
Too much trouble.

**Comment by pradyunsg** [comment]
Ok.

**Comment by Monnoroch** [comment]
Try to type theese names in the terminal too often and you'll hate them.

**Comment by pradyunsg** [comment]
I use shell completions and corrections a lot now so I don't mind that. 

But I do know the pain. :)
