### ISSUE TITLE
Variables from @import no longer highlighted

### ISSUE THREAD

**Issue by ryanderson** [Monnoroch/ColorHighlighter#262]
This used to work, but recently has stopped. Same issue as #234 but I am not seeing it fixed.

Colors highlight in my variables.scss file and/or within the same .scss file, as expected. But colors are not highlighted when using @import to link to the variables.scss and use a color from it in a different .scss file.

**Comment by Monnoroch** [comment]
Please, provide a minimal example, as well asST version and OS.

**Comment by ryanderson** [comment]
Got it! I was doing some more tests and preparing screenshots for you and luckily solved the issue: I was using `@import 'variables';` to import my _variables.scss partial file...but now I am needing to add the `_` to have the ColorHighlighter plugin work as before. So having this `@import '_variables';` instead now works.
