### ISSUE TITLE
linux color pick

### ISSUE THREAD

**Issue by twxia** [Monnoroch/ColorHighlighter#263]
Hi,
this package is awesome :+1: 

but linux color pick feel a little old-fashion.
![screenshot from 2015-09-23 22 08 21](https://cloud.githubusercontent.com/assets/2068895/10047223/a4e9c2ee-623f-11e5-8479-2406c427f5bf.png)

It'll be great if change the design like this one:
https://github.com/mbasaglia/Qt-Color-Widgets/blob/master/gallery/README.md#colordialog

**Comment by Monnoroch** [comment]
This is an open source project.
I'll be waiting for the pull request!
