### ISSUE TITLE
Errors in Sublime Console

### ISSUE THREAD

**Issue by zmLGBBM** [Monnoroch/ColorHighlighter#272]
I'm using Windows 10 64bit with Sublime Text 3.

**Color Highlighter** works fine. However, when `right click` on one of the `colored` string, the sublime `console` prints many errors:

    'utf-8' codec can't decode byte 0xce in position 0: invalid continuation byte
    Unable to extract text from the clipboard, available formats: 
    TypeError: String required
    TypeError: String required
    TypeError: String required
    TypeError: String required
    TypeError: String required
    Unable to extract text from the clipboard, available formats: 
    Unable to extract text from the clipboard, available formats: 
    Unable to extract text from the clipboard, available formats: 

Should I be worry about it? Thanks.

**Comment by Monnoroch** [comment]
Dunno, not a CH problem.

**Comment by zmLGBBM** [comment]
@Monnoroch Hey, how do you guys debug plugins? Instead of `print()`..

**Comment by Monnoroch** [comment]
@zmLGBBM With jedi force.

**Comment by zmLGBBM** [comment]
@Monnoroch jedi force?

**Comment by Monnoroch** [comment]
@zmLGBBM Exactly!

**Comment by zmLGBBM** [comment]
@Monnoroch Haha, I don't think `print` is as great to compare.
