### ISSUE TITLE
Add support for SVG

### ISSUE THREAD

**Issue by jacobbuck** [Monnoroch/ColorHighlighter#276]

**Comment by Monnoroch** [comment]
What is this supposed to mean?

**Comment by jacobbuck** [comment]
Sorry, should've elaborated.

In SVGs there are attributes such as `color`, `fill`, `stroke`, `stop-color`, `flood-color` and `lighting-color` which use the `color` property. It would be great if those were highlighted.

**Comment by Monnoroch** [comment]
Try to add the .svg extension to the supported extensions list.

**Comment by jacobbuck** [comment]
Oh I see now. Thanks :+1:
