### ISSUE TITLE
Wich Color Picker? [FIXED]

### ISSUE THREAD

**Issue by LOQUILLO** [Monnoroch/ColorHighlighter#279]
Wich Color Picker must to load.
This: 
![color_picker_default](https://cloud.githubusercontent.com/assets/1308190/10732655/151eff32-7bc9-11e5-8ace-96ab686fdb3f.png)

or this newest:
![color_picker_new](https://cloud.githubusercontent.com/assets/1308190/10732768/927fe220-7bc9-11e5-86cc-cc9728424ae9.png)

By default load the frist one, but the second is into \Color Highlighter\ColorPicker\ and how to do for load.

SOLVED:
I had deleted the folder Color Highlighter into \Sublime Text 3\Packages\User\ and solved the problema. Color Highlighter had create one new with the last Color Picker newest.

**Comment by Monnoroch** [comment]
This should fix the problem: https://github.com/Monnoroch/ColorHighlighter/commit/08e612da09938d1a8a7ba57967427d7f0893ab11.
