### ISSUE TITLE
Color works on first load of ST3, but after making changes it no longer highlights correctly

### ISSUE THREAD

**Issue by cvax** [Monnoroch/ColorHighlighter#285]
When I first load a css file the filled colors are all correct. When I change the color by typing in new values, it shows the old color unless I click on the color. If I move the cursor away it shows the old color. I have to save the file to get the correct color showing. If I wait a while, the correct color finally comes up.

**Comment by Monnoroch** [comment]
It's not a bug, it's a feature. Updating the colors for the whole file only happens during some window events.
In addition to what you said, you could also go to another tab and back.

Color highlighting for the whole file is a very expensive operation: very big regexes for the whole file. Unfortunately, I can't get the exact change you made from ST API, so I can't only run matching for the specific line, for example.
