### ISSUE TITLE
Some colors render as white (that aren't white!)

### ISSUE THREAD

**Issue by farzher** [Monnoroch/ColorHighlighter#286]
![](http://i.imgur.com/KTZoCqu.png)

This should be black, if I tweak it a bit, it changes colors, but putting it to `#1c1c1c` always goes white

**Comment by Monnoroch** [comment]
ST region renderer might we weird.
Check your color scheme file modified by CH, does it have a region for that color?
It should. And you can manually check, that the background color set by CH is corrent.
It's just that ST renders colors depending on the color scheme in some ununderstandable way.
