### ISSUE TITLE
Support for hex color codes with 0x prefix

### ISSUE THREAD

**Issue by ImDeity** [Monnoroch/ColorHighlighter#290]
The [Luxe / Haxe game engine](http://luxeengine.com/docs/) uses color codes in the format `0x[hex code here]` as shown below:

`new Color().rgb( 0xFFFFFF ),`

The `0xFFFFFF` format seems to not be recognized with ColorHighlighter. Please add support.

**Comment by Monnoroch** [comment]
You can add a regex to the  .sublime-settings file to highlight those.

**Comment by ImDeity** [comment]
Wow that was fast. Thanks for the info.

**Comment by Monnoroch** [comment]
Actually, CH should already support this format, is't called hex8 in settings.
Maby you need to enable CH for your file extension?

**Comment by ImDeity** [comment]
You're right again, I've now added `.hx` (Haxe language) to the `file_exts` setting and it is now working.

Thanks!
