### ISSUE TITLE
Doesn't work well on sublime 3103

### ISSUE THREAD

**Issue by Epskampie** [Monnoroch/ColorHighlighter#294]
Sublime text just released a new version, 3103. However, colorhiglighter doesn't seem to work well anymore. Colors don't show up when the cursor is in a color, and the "static" "ha_style" fails to update properly when changing the color.

I sorely miss it, since I've grown to love this plugin. If anyone points me in the right direction I'm willing to create a pull request that fixes the issue.

**Comment by eugenesvk** [comment]
@Epskampie strange, this part is working fine for me on an OS X 10.11.3 with ST3 3103.
However, gutter icons are not displayed even after I've installed ImageMagick. Do those work for you or not?

**Comment by Epskampie** [comment]
Forgot to mention, I'm using linux, Ubuntu 15.10. Gutter icons work for me.

However, after restarting my computer and sublime, everything now seems to work again? Guess something was updating in the background, or something else is wrong with my computer.

**Comment by Monnoroch** [comment]
Restarting your computer seems like too much :)
It should of worked after just restarting ST.

**Comment by Epskampie** [comment]
I know, I just left for the weekend, noticed the activity on this issue, retried, and now it works again. :-) Don't know what caused that exactly...
