### ISSUE TITLE
New color identification / refresh

### ISSUE THREAD

**Issue by maxjosino** [Monnoroch/ColorHighlighter#297]
Hi
When i open any file the plugin show all the colors correctly. The problem is when i try to change it to another color. It does not recognize the new value as a new color and i can only check that new color if i click/put the cursor there or command+tab to another application and then back to sublime.

Is there any way to make something like an auto refresh?
FYI, i teste it with .css; .html and .json files

**Thank you for all the hard work!**

**Comment by Monnoroch** [comment]
Auto refreshing would be really slow, so no, until ST doesn't have an app to know the presice change you made, I can't do autorefresh, since it has to be for the whole file.

**Comment by maxjosino** [comment]
I see. 
Okay! Thanks for the quick response!
