### ISSUE TITLE
Colours not accurate with gc's 'fix themes' option turned on

### ISSUE THREAD

**Issue by davenewt** [Monnoroch/ColorHighlighter#302]
Hi, first of all thanks for this. Have been looking for a plugin that shows colours like this for a while!

Unfortunately the colours I'm getting in ST3 aren't accurate (the files generated for the icons are correct, however).

I read up on this previous issue thread: https://github.com/Monnoroch/ColorHighlighter/issues/179 and thought I might've found a fix, but no.

Here's what it looks like for me using Preferences > Color Scheme > Gutter Color > cobalt2.gcfix ...

![screenshot](http://content.screencast.com/users/DWStroud/folders/Jing/media/6b3705c7-a1e4-4a2b-b27f-8466f42664dd/00000006.png)

Any help appreciated.

**Comment by Monnoroch** [comment]
Nothing I can help you with. CH uses the right colors, which you can clearly see in icons folder.
ST just messes with them for some themes. My guess is that either ST has a bug, or the theme is broken in some way.

**Comment by davenewt** [comment]
OK thanks for the quick reply anyway!
