### ISSUE TITLE
Is it possible to exclude certain formats?

### ISSUE THREAD

**Issue by oakley808** [Monnoroch/ColorHighlighter#305]
Is it possible to turn off highlighting for named colors, but still highlight rgb or other formatted colors?

**Comment by Monnoroch** [comment]
Yes, just delete stuff from a dictionary in colors.py.

**Comment by oakley808** [comment]
Thanks! 
Might be a worthy user preference/option to consider.

**Comment by Monnoroch** [comment]
Good idea, this is open source, feel free to contribute.
