### ISSUE TITLE
CAPITAL Letters in colours

### ISSUE THREAD

**Issue by rossisen** [Monnoroch/ColorHighlighter#306]
I have a custom class with static vars with colours like BLUE and AQUA - I would like them to light up like blue and aqua do.  I tried to unzip, hack the color.py file, and package up with no luck.

It could be nice to have the option of having the named colours be case insensitive.

**Comment by Monnoroch** [comment]
Could be nice indeed. This is an open source plugin, you're very welcome to contribute!

**Comment by rossisen** [comment]
I am pretty new to this.  I would need at least an outline of the best way to proceed.  My hacking the color.py file didn't test out.
