### ISSUE TITLE
White colour is highligted as black for bright theme

### ISSUE THREAD

**Issue by jiaming10** [Monnoroch/ColorHighlighter#309]
Hi, I am facing this problem, where 'white' or #FFF is highlighted as black, but #FFFFFE is highlighted properly. Is this by design? I'm using demo values from issue #299.

![demo](https://cloud.githubusercontent.com/assets/8718138/15284415/b7ec2fa0-1b83-11e6-95df-c2eeaa9a9824.png)

**Comment by Monnoroch** [comment]
That's a ST bug, not the plugins. Discussed multiple times already.

**Comment by jiaming10** [comment]
Alright then, is there any workaround you can suggest? Or any issue can I reference? Thanks.

**Comment by Monnoroch** [comment]
Nope. ST just displays it like that in bright themes for some reason. Have no idea, why.
