### ISSUE TITLE
Incorrect rgb highlighting

### ISSUE THREAD

**Issue by FeBe95** [Monnoroch/ColorHighlighter#316]
This rgb value should not be highlighted/ recognized for conversion:
![bug](https://cloud.githubusercontent.com/assets/7470739/16690616/1a375292-4529-11e6-878c-36fe402f5651.png)
The color picker detects the following color:
![cp](https://cloud.githubusercontent.com/assets/7470739/16690737/a5a6766e-4529-11e6-8c86-989dfd688e93.png)

**Comment by Monnoroch** [comment]
Will be fixed in the new version: #366.
