### ISSUE TITLE
Color conversion buggy

### ISSUE THREAD

**Issue by FeBe95** [Monnoroch/ColorHighlighter#317]
Colors with r,g,b values that do not have a single char (0-F) hex equivalent, but rather need two characters (00-FF), do not convert correctly.
For example:
`rgb(170, 187, 85)` (=`#AABB55`) gets converted just fine to `#AB5` (sharp3) while
`rgb(171, 188, 85)` (=`#ABBC55`) gets converted to `#ABC5`, which isn't a correct color code.
A correct conversion should output `#AB5`, with `BC` cutting the `C` just like rgb cuts the alpha value from rgba. This happens with all sharp and hex formats.

**Comment by Monnoroch** [comment]
The code is just too complicated to fix it. Will be fixed in the new version: #366.
