### ISSUE TITLE
Changes only applied when restarting ST3

### ISSUE THREAD

**Issue by tansongyang** [Monnoroch/ColorHighlighter#320]
My issue is similar to #285. However, no matter what I do (move cursor, save file, switch tabs), I can't get a new color to display after I type it in. New colors are only applied when I restart.

ST3 build 3114 on Windows 7.

**Comment by Monnoroch** [comment]
The original issue also explains that this is a feature. I might add a setting to enable what you want in the new version.

**Comment by tansongyang** [comment]
Thanks for responding. I must have missed that. But I would appreciate having that setting; do you need help with a PR? Either way, I'm closing this issue since my question is answered.

**Comment by Monnoroch** [comment]
Nope, don't need help, just need to think how would I implement it.
