### ISSUE TITLE
hsl(h, s, l) is not highlighted

### ISSUE THREAD

**Issue by CapacitorSet** [Monnoroch/ColorHighlighter#337]
I'd love it if this also worked on HSL colors, since I use them extensively.

**Comment by davmillar** [comment]
@CapacitorSet it seems to work for me in the context of Sass (and CSS in general). What kind of code are you writing, and how are saturation and lightness represented in it?

![image](https://cloud.githubusercontent.com/assets/576958/26741538/5c0fc72a-479f-11e7-9d7c-c16611add719.png)
