### ISSUE TITLE
Clean after yourself properly when uninstalling!!

### ISSUE THREAD

**Issue by gotofritz** [Monnoroch/ColorHighlighter#341]
Hi. I have been pulling my hair trying to work out why BracketHighlighter wasn't working, and it was all because ColorHighlighter makes its own copy of a theme which is annoying enough, but worse, it sticks around in the local/session.sublime_session file even after uninstalling! 

Please be a good citizen and clean up everywhere when uninstalling, thanks!

**Comment by gotofritz** [comment]
Also remove ColorHighlighter folder from the User folder

**Comment by dustinbolton** [comment]
How do you fix this?
