### ISSUE TITLE
Inconsistent display in other panes (multicolumn)

### ISSUE THREAD

**Issue by VipSaran** [Monnoroch/ColorHighlighter#347]
My User sublime-settings:

```
{
	"enabled": true,
  "default_keybindings": false,
	"ha_style": "outlined"
}
```

Left (default) pane (1st column) behaves as expected: color values in a CSS file are only outlined and when the cursor is in the value, the color text bg color is shown accordingly.

But, when the same file is opened (via "New View into File") in another pane (e.g. 2nd column), then only the outline works and entering of cursor does nothing.

Same happens other way around -- when a file is first opened on right, then another instance of it is opened on left. In that case the left one (i.e. "copy") doesn't behave correctly.

Probably something to look into.

**Comment by Monnoroch** [comment]
@VipSaran #366.
