### ISSUE TITLE
change key binding not working?

### ISSUE THREAD

**Issue by leafiy** [Monnoroch/ColorHighlighter#356]
Default key `super+shift+a` has a conflict to system default `expand select`

I add these to `Key Binding - User`, but its not working

` {
		"keys": ["super+shift+."],
		"command": "color_convert",
		"context": [
			{
				"key": "color_highlighter.color_convert"
			}
		]
	}`

When just open sublime for 2-3s, the default `expand select` works, but once the console shows `color hightligher` loaded, `super+shift+a` back to `color_convert`

**Comment by leafiy** [comment]
figure it out, I also have to add default `super+shift+a` to `Key Bindings - User`

my bad ... close

**Comment by pattiereaves** [comment]
I have the same issue. How did you fix it? This is what I have in my user keymap:
```
	{
		"keys": ["ctrl+super+shift+c"],
		"command": "color_picker",
		"context": [
			{
				"key": "color_highlighter.color_picker"
			}
		]
	},
	{
		"keys": ["ctrl+super+shift+a"],
		"command": "color_convert",
		"context": [
			{
				"key": "color_highlighter.color_convert"
			}
		]
	},
	{ "keys": ["super+shift+a"], "command": "expand_selection"}
```

... but it doesn't restore expand selection.
