### ISSUE TITLE
Sniff SCSS variables in other files in the ST3 project

### ISSUE THREAD

**Issue by ronilaukkarinen** [Monnoroch/ColorHighlighter#357]
Hello there. As I moved back from Atom to ST3, I was missing the color highlight feature that recognizes the variable that is set in another file. For example, I have `_config.scss` with all the colors set up and other files like `_nav-layout.scss` where I use the variables like this:

![Screenshot](https://rolle.wtf/ColorHighlighter-issue.png "Screenshot")

Those variables are not showing the color, which I would prefer. Is this possible in any way with ColorHighlighter? [All Autocomplete](https://github.com/alienhard/SublimeAllAutocomplete) recognizes the variables in other files, so at least that part is possible. Any thoughts?

**Comment by rgpublic** [comment]
I'm also missing this. There is "color_variables_files" but it's clumsy. It'd be much better if it could autodetect them in all .scss files.

**Comment by haizdesign** [comment]
This works if you added the path to your partial (@import) file in the .sublime-project file like this:

{
	"folders":
	[
		{
                      "path": "."
                }
	],
       "color_variables_files": "/Users/yourname/path/to/partial/file/wp-content/themes/themename/_colors.scss",
}

However, with the 8.0 new version, this has stopped working until you delete your preferences and reset them.

**Comment by ronilaukkarinen** [comment]
I have tried everything, including .sublime-project suggested above, but not getting this to work. Using the latest version. Similar issues: #296 #271

**Comment by Monnoroch** [comment]
https://github.com/Monnoroch/ColorHighlighter#variables-highlighting

**Comment by ronilaukkarinen** [comment]
@Monnoroch Thanks for the info, good to know it's planned in the future. 👍
