### ISSUE TITLE
How to highlight all the colors???

### ISSUE THREAD

**Issue by ckizer** [Monnoroch/ColorHighlighter#358]
The instructions say this:

**"You can also turn on highlighting all colors at once. This mode has own highlighting style, so you can highlight all colors with underline and selected colors with filled rect."**

But doesn't explain how to or what setting. I want all the colors in the entire document to be solid blocks all the time.

**Comment by davmillar** [comment]
@ckizer to highlight all, you'll need to use the setting **ha_style** and for solid blocks, set it to **Filled**. Issue #261 has a rewrite of the instructions file, but that also seems to have missed this detail.

**Comment by philiplambok** [comment]
Still didnt work for me
