### ISSUE TITLE
Themes getting added to User theme directory automatically

### ISSUE THREAD

**Issue by webdevnerdstuff** [Monnoroch/ColorHighlighter#360]
ST3: Build 3126
OS: Win7
CH Package Version: 2017.05.31.17.18.02

Every time I make a change to my custom theme, I get a new one added into _**Color Scheme > User > Color Highlighter > themes**_ in Sublime and in the directory _**Packages > User > Color Highlighter > themes**_. I even deleted this folder and it just recreates it and copies the active theme selected over.

Is this by design or a specific setting? I looked at your docs and I don't see this as being part of the functionality, but it's definitely this plugin that's doing it as it does not occur when I disable it. This happens on my Win7 computer, I haven't checked if it does the same on my MacBook. It's not a huge problem really, but when I'm editing my own theme and testing it add's a lot of them in there, which caught my attention.

**Comment by Monnoroch** [comment]
It is by design. Creating a new theme and writing some settings to it is the only way to create colored boxes for highlighting colors. Unfortunately, this doesn't work when you create your own theme, yes, but nothing can be done about it for now.

**Comment by webdevnerdstuff** [comment]
Thank you for the explanation. I actually did create my own theme, and it does save that theme over there as well and the highlight colors work perfectly.
