### ISSUE TITLE
Even after removing package my "color_scheme" is overridden by Color Highlighter

### ISSUE THREAD

**Issue by GlassGruber** [Monnoroch/ColorHighlighter#363]
Hei there, 
I've removed your plugin via `Package Control: Remove package`, though somehow there is something that is still overriding my `color_scheme` path in user settings for sublime. Sublime simply ignore my setting and search the theme in `Packages/User/Color Highlighter/themes/predawn (SL).tmTheme` throwing an error (I've removed the folder manually). 

I can't find where this override happens. As of now I recreated the folder and placed my file there, though as you can tell is not an ideal solution. Any suggestion? 

Thank you for your time, your plugin is pretty useful, I'm removing it just because I'm not using it atm.

**Comment by Monnoroch** [comment]
If the plugin is removed there's no possible way it can affect anything. Just manually set the color scheme in your settings file to whatever you want. If you've told package control to remove it but it didn't, it's a package control bug I can not help you with.

**Comment by GlassGruber** [comment]
Thank you for your answer! 
Your point is valid, and while not directly helpful it indeed helped me getting out of this issue that bugged me for couple hours: I've reinstalled your plugin and uninstalled again via _PC_, this way the issue reported got somehow solved. 

I have to say that I had your plugin installed for a very long time, maybe something got borked time ago preventing updates for the package. 
Side note: the _Color Highlighter_ folder is still present in the `Packages/User` directory after uninstall (I think is related to #341)

Thank you.
