### ISSUE TITLE
Color picker not working

### ISSUE THREAD

**Issue by PedroFumero** [Monnoroch/ColorHighlighter#364]
I'm pressing ``ctrl + shift + c`` but nothing shows up, also try enter with ``ctrl + shift + p`` and typing Color Picker, but nothing happens.

After to hit command to run color picker, console shows me the next:

> Traceback (most recent call last):
>   File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 818, in run_
>     return self.run(edit)
>   File "C:\Users\Pedro\AppData\Roaming\Sublime Text 3\Packages\ColorPicker\sublimecp.py", line 365, in run
>     color = cp.pick(self.view.window(), selected)
>   File "C:\Users\Pedro\AppData\Roaming\Sublime Text 3\Packages\ColorPicker\sublimecp.py", line 316, in pick
>     proc = subprocess.Popen(args, stdout=subprocess.PIPE)
>   File "./python3.3/subprocess.py", line 784, in __init__
>   File "./python3.3/subprocess.py", line 980, in _get_handles
>   File "./python3.3/subprocess.py", line 1030, in _make_inheritable
> OSError: [WinError 6] Controlador no válido

I'm using sublime text 3 with Windows 7

**Comment by PedroFumero** [comment]
I'm done.

**Comment by alexkadis** [comment]
Did you figure out a solution to this? I'm running into the same problem.

**Comment by Monnoroch** [comment]
Guys, please try the new version: #366. It lacks preprocessor variables support, but everything else is working and it's supposed to be much faster.

**Comment by Monnoroch** [comment]
@PedroFumero you're using ColorPicker plugin, which is not this pne (ColorHighlighter) and is apparently conflicting with this one.

**Comment by alexkadis** [comment]
@Monnoroch I uninstalled ColorPicker before installing ColorHighlighter. I've also tried the new version (v8.0) and I'm still unable to get the plugin to work. Here's my entire [console log](https://github.com/Monnoroch/ColorHighlighter/files/1318471/sublime-console.log.txt).

**Comment by Monnoroch** [comment]
@alexkadis yep, this is a ptoblem with alpha version: you need to install it in `Packages/color_highlighter`, not `Packages/Color Highlighter`. The dir was changed because spaces in file names are generally bad.

**Comment by alexkadis** [comment]
@Monnoroch Hm. Changed that, still having the issue: 
[sublime-console.log.txt](https://github.com/Monnoroch/ColorHighlighter/files/1318516/sublime-console.log.txt)

**Comment by Monnoroch** [comment]
@alexkadis can you please add `print(color_picker_resource)` right after `color_picker_resource = path.color_picker_binary(path.RELATIVE)`.

The problem is I don't have a windows machine, so I haven't tested resorce and file paths on windows. I'm sorry you have thees problems, and would appreciate if you'd help me fix them.

**Comment by alexkadis** [comment]
@Monnoroch Happy to help! I prefer Macs, so I'm not sure how to troubleshoot this on Windows. (My work computer is Windows, home is Mac.)  I'm actually about to step out for a long weekend, hope you don't mind that I get back to you on Monday.

**Comment by Monnoroch** [comment]
No problem, have a nice weekend :)

**Comment by alexkadis** [comment]
Ok, I figured it out. In path.py, use your ``normalize_path_for_st`` function.

Change line 105 to:
``return normalize_path_for_st(os.path.join(color_picker_path(relative), _color_picker_file()))``

Change line 115 to:
``return normalize_path_for_st(os.path.join(packages_path(relative), PLUGIN_NAME, "ColorPicker", _color_picker_file()))``

Change line 128 to:
`` return normalize_path_for_st(os.path.join(themes_path(relative), file_name))``

**Comment by Monnoroch** [comment]
@alexkadis I've recently updated the branch and a similar fix to yours was implemented. Please test the newest version.

**Comment by alexkadis** [comment]
Works! Thanks.

**Comment by Monnoroch** [comment]
@alexkadis please, report any bugs you might find to #366.
