### ISSUE TITLE
No Gutter Icon on ST-3126 in WIN10 32bit

### ISSUE THREAD

**Issue by APSlee** [Monnoroch/ColorHighlighter#367]
There is a previous issue #361  about the gutter icon problem. I follow his instruction but problem still. 

First, there is no version 6.9.8 at the link he provided. So, I tried version 6.9.9-11, but didn't work neither.

Then I tried 6.9.3-0, 6.2.7 and all the version I can find(I can't find 6.9.8 on the net), but still didn't work.

Did I downloaded the wrong version? or used the wrong setting? 
It is right to set the "convert_util_path" : "D:/Program Files/ImageMagick-6.9.9-11-portable-Q16-x86", RIGHT?

Is there anybody has the same problem? And @Monnoroch which version of ImageMagick did U use? 

THANKS!

**Comment by Monnoroch** [comment]
I use Linux, so I can't help here. My windows friends tell me that everything's fine given that you configure the `icon_factory.convert_path` setting correctly.
