### ISSUE TITLE
ColorHighlighter does not see the Sass-Scss module.

### ISSUE THREAD

**Issue by Devinora** [Monnoroch/ColorHighlighter#369]
http://joxi.ru/Vrwn9MlTKw0ydA

**Comment by Monnoroch** [comment]
Yep, the variables system is far from perfect. Right now I'm in the process of reimplementing it as part of the new version. Here's the alpha: #366. It does not support variables, but this is the only missing feature.

**Comment by Devinora** [comment]
Thanks for answering. I'm from Ukraine and I do not know much English. This
was the problem in finding the answer.

2017-09-27 1:44 GMT+03:00 Max <notifications@github.com>:
