### ISSUE TITLE
Doesn't highlight colors in vue files

### ISSUE THREAD

**Issue by el-jacko** [Monnoroch/ColorHighlighter#374]
Hi,

Since the last update the plugin doesn't highlight anymore colors in .vue files.
In .css, .sass, .scss files it just works fine.

The default settings file is empty ...
No errors in the console.

OS: Mac OS X v10.12.6
Sublime Text: v3 Build 3143

Cheers

Update: Also in .tmTheme files it does not work anymore.
Update: I don't know if it worked before, but it doesn't work in .js, .php, .html files too.

**Comment by Eugene-nsk** [comment]
I have the same problem. Look at installation video https://yadi.sk/i/GhEiYAQX3NN2dH

**Comment by Monnoroch** [comment]
You probably neer to update plugin settings and add all file extensions you need to support. The new default settings only include stylesheets. If you thing some extension should be enabled by defauls, please send a PR.

**Comment by Monnoroch** [comment]
I've addd a FAQ section to the README to explain that to everyone.
