### ISSUE TITLE
Version 8 doesn't work

### ISSUE THREAD

**Issue by tiagoporto** [Monnoroch/ColorHighlighter#378]
My sublime text updated and stopped working. What happened?

Im using sublime text 3 on mac OS.

**Comment by Monnoroch** [comment]
This bug report does not provide any information on what is the problem.

**Comment by tiagoporto** [comment]
@Monnoroch The colors doesn't highlighted anymore.

Even in .css, .sass, .scss and .stylus

![screen shot 2017-10-02 at 11 00 23 am](https://user-images.githubusercontent.com/3688905/31081547-97d9db24-a762-11e7-8717-2052b245c080.png)
![screen shot 2017-10-02 at 11 11 24 am](https://user-images.githubusercontent.com/3688905/31081548-97dd7220-a762-11e7-98a0-d6bce44f111d.png)

**Comment by Monnoroch** [comment]
What OS and ST version do you use? What does the log say?

**Comment by tiagoporto** [comment]
MacOS Sierra version 10.12.6
Sublime text 3.0 Build 3143

```sh
File "./python3.3/codecs.py", line 896, in open
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tiagoporto/Library/Application Support/Sublime Text 3/Packages/Color Highlighter/ColorHighlighter.sublime-settings'
```

I've try to reinstall but the error persists

**Comment by OscarDeDios** [comment]
Hi.
With Windows 8 and sublime text 3 I see the color in a new line just below the code when I put the cursor in the color.

![image](https://user-images.githubusercontent.com/722614/31081941-c180e2b2-a78d-11e7-9bde-5c766720e0ab.png)

Thanks.

**Comment by Monnoroch** [comment]
Can you check if `/Users/tiagoporto/Library/Application Support/Sublime Text 3/Packages/Color Highlighter/ColorHighlighter.sublime-settings` actually exists or not?

> With Windows 8 and sublime text 3 I see the color in a new line just below the code when I put the cursor in the color.
I don't see any problems or questions here.

**Comment by tiagoporto** [comment]
The folder doesn't exist.

![screen shot 2017-10-02 at 11 25 59 am](https://user-images.githubusercontent.com/3688905/31082155-808e9e1c-a764-11e7-8894-1dc4b079495d.png)

**Comment by Monnoroch** [comment]
Can you please attach the whole log file?

**Comment by OscarDeDios** [comment]
I don't see any problems or questions here.

Well, the "problem" is the color appears in a new line below the code, is it the normal behaviour?. It's not important but I thought it could help you and it was related to this issue. I'm sorry if I'm wrong.

Thanks four your plugin Monnoroch.

**Comment by Monnoroch** [comment]
@OscarDeDios if you read the readme you will find a section about configuring the plugin which explains what settings are there and what do they do. You can configure it however you like.

**Comment by tiagoporto** [comment]
@Monnoroch After reinstall and reopen  sublime text twice the plugin started to work, but with the same behaviour reported by OscarDeDios, and some other strange behaviors

![screen shot 2017-10-02 at 11 33 14 am](https://user-images.githubusercontent.com/3688905/31082473-7ed27ec6-a765-11e7-8ea6-7cadd207d9c3.png)

The color here is #000
![screen shot 2017-10-02 at 11 38 25 am](https://user-images.githubusercontent.com/3688905/31082798-388668dc-a766-11e7-9a31-dcb84ec1a4b9.png)
With the cursorin the color
![screen shot 2017-10-02 at 11 35 53 am](https://user-images.githubusercontent.com/3688905/31082626-e084d7fe-a765-11e7-9681-14b93c936372.png)

With the color name doenst work
![screen shot 2017-10-02 at 11 36 51 am](https://user-images.githubusercontent.com/3688905/31082704-ffb3f808-a765-11e7-8400-9d96391767b0.png)

**Comment by Monnoroch** [comment]
@tiagoporto color names indeed do not work because https://github.com/Monnoroch/ColorHighlighter#the-plugin-doesnt-work-in-htmljsvueother-files. I don't see any other weird behaviour.

**Comment by samrap** [comment]
I am having the exact same issues on OSX. I doubt this is an issue with my configuration as I am using the default configuration. Unless the default configuration is supposed to highlight everything in white and have giant underlines then I think this is a bug.

**Comment by Monnoroch** [comment]
@samrap The underlines are supposed to be there, if you want to disable them, please read the readme. Highlighting everything in white is a bug though, but unfortunately I don't have an OSX machine to test it myself so I would need help with that.

**Comment by samrap** [comment]
Ok, is there a way to change the height of the underlines? In the previous version they were very thin, maybe 2px or 3px. I really liked that, would be nice to be able to adjust that. I can try looking into this some more on my machine. I will let you know if I find anything :)

**Comment by Monnoroch** [comment]
@samrap please read the readme, all the different highlighting styles are explained in great detail there. The only feature that was removed is the variables, everything else is stil there and only the default settings have changed.

**Comment by Monnoroch** [comment]
Also, can you guys tell me what color shcemes do you use? I've checked all the default ones and it's working perfectly (on linux).

**Comment by samrap** [comment]
I have tested in 20+ color schemes including the default Monokai. 

Strange, but I was able to perform the following steps in order to get it to work:

1. Uninstall Color Highlighter
2. Restart ST3
3. Install Color Highlighter
4. Change color scheme

Upon completing step 4, the colors seem to be highlighting properly.

**Comment by Monnoroch** [comment]
Strange indeed. Can you now break it again? If so, can you set `"debug": true` setting and post the complete log file here?

**Comment by samrap** [comment]
I can't seem to break it 😅

**Comment by Monnoroch** [comment]
Perhaps the problem only appears when you upgrade. Hard to test that one...

**Comment by samrap** [comment]
Indeed. Might I recommend placing the following in your project readme and ST3 release notes?

- Stating that users may need to switch their color scheme for the update to be applied properly
- Making it more clear that the plugin is much more configurable and therefore will most likely work differently out of the box than in previous versions. Users should read through ALL options and tweak the configuration to their liking.

In my experience, users expect either A) an update to enhance but not change the experience or B) a clear message that some configuration and setup should be expected.

Thanks for your work on this, it's a great package! :)

**Comment by tiagoporto** [comment]
@Monnoroch my color scheme is Blackboard

**Comment by Monnoroch** [comment]
@seeeeei can you send a PR? I tried my best to describe all the settings.

**Comment by branditodesigns** [comment]
![image](https://user-images.githubusercontent.com/22213052/31104943-1a7e02de-a82c-11e7-9035-49f49e411680.png)

when clicking on the 'colours' they too are going to a new line like others have been

**Comment by Monnoroch** [comment]
@branditodesigns I don't understand. Please provide all needed information: ST version, OS, logs.

**Comment by Monnoroch** [comment]
@samrap I actually was able to reproduce the bug on ST2, but not ST3. The problem seems to be in ST2 itself though: it doens't reload the `.tmTheme.cache` file when the color scheme file changes. Are there `.tmTheme.cache` files in `User/Color Highlighter/themes` on your system?

**Comment by ihodev** [comment]
@Monnoroch Just a note. You can use `.hidden-thTheme` instead of `.tmTheme.cache`. It acts like `.tmTheme` but every color scheme activator ignores it. Fits extremely nice to your case.

**Comment by Monnoroch** [comment]
@ihodev I don't use anything. When I cange a color cheme file the "cached" version gets automatically updated. Only not always in ST2-linux and possibly some other systems. ST3-linux doesn't have these cached files at all (maybe ST3 caches them in-memory).

**Comment by ihodev** [comment]
Ah, I've just tested. 

ColorHighlighter created color scheme in `Packages/User/Color Highlighter/themes/<name>.tmTheme`, Sublime Text created the cached copy in `Cache/User/Color Highligter/themes/<name>.tmTheme.cache`. 

Everything works as expected on Windows.

Also reloading issues may be related to https://github.com/SublimeTextIssues/Core/issues/1154#issuecomment-296577762

**Comment by Monnoroch** [comment]
@ihodev interesting, thanks! I'll implement a forces cleanup then.

**Comment by ihodev** [comment]
Also I'll recommend you to change the extension of the generated color scheme to `.hidden-tmTheme`, this will hide all clones from `UI: Select Color Scheme` list.

**Comment by Monnoroch** [comment]
@ihodev will it work with ST2?

**Comment by Monnoroch** [comment]
@ihodev unfortunately it doesn't even work with ST3. If I write the generated file as `.hidden-tmTheme` it just refuses to set the view color scheme to it and falls back to the default one from preferences.

**Comment by ihodev** [comment]
Hmm, it should work, you just need to set `path/<name>.hidden-tmTheme`, not `path/<name>.tmTheme`.

**Comment by ihodev** [comment]
> It doesn't reload a hidden scheme file when I update it dynamically.

That is possible, I'll play with that later.

**Comment by Monnoroch** [comment]
@ihodev well, I've just tried that :) You can look at the branch "hidden" to verify that I'm doing it correctly.

@OscarDeDios, @samrap, @branditodesigns please test the new 8.0.6 version once it propagates to PC. It should fix the issue with white inline color highlighting.

**Comment by samrap** [comment]
@Monnoroch I did not see those cache files, but in any case everything seems to be working now :) Thanks for the help!

**Comment by DanielSmedegaardBuus** [comment]
Hey guys! Just helped out my designer colleague with this. I haven't used the plugin myself before as I'm not a frontender, but I installed it and had the same issues he had: Changes to settings doesn't seem to do anything, and the only way to get the colour shown is that weird behaviour where it adds an extra line with a coloured block beneath the text.

I tried installing ImageMagick on both our machines, and after that, everything works as advertised. @Monnoroch , I think you may just have an assumption somewhere in your code that the imagemagick binary exists, and when it doesn't it breaks something pretty badly.

Cheers :)

PS: For this to work, you must make sure that imagemagick is in the path that Sublime Text reads. Which, for macOS means that it must be somehow in the system's path, or you need to start Sublime from the console, if it's only in your local path (`/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl`).

**Comment by Monnoroch** [comment]
@DanielSmedegaardBuus I'm going to need logs to debug any issues you had. Would appreciate if you'd help me catch the bug.

**Comment by kud** [comment]
I had the same problem on 3144.
How to fix it

**Comment by kud** [comment]
I did it again and I had no troubles about my theme. Weird.

**Comment by Monnoroch** [comment]
Guys, you really do need to provide more info on your problems, including OS, ST version, screenshots and logs.

**Comment by kud** [comment]
I don't see the point to give these informations as it works for me.

But if you want:

- ST: 3144 dev
- macOS: 10.12.6

**Comment by Monnoroch** [comment]
Well, you said
> I had the same problem on 3144

So I though there is a problem.

**Comment by kud** [comment]
I had yeah even by removing the plugin via package control but with removing the Color Highlighter folder, it now works properly. :)

**Comment by lec00q** [comment]
I have (the same? similar?) issue:

- macOS: 10.12.6
- ST: 3143

![screen shot 2017-10-05 at 20 09 28](https://user-images.githubusercontent.com/8955202/31242989-1f4d57d6-aa09-11e7-867a-308d2037f228.png)

This is the error I got from the logs (debug enabled):

```
ColorHighlighter: action=start st=st3
ColorHighlighter: action=create_icon style=circle color=#ffffffff
Traceback: error.

Output:


Error:
convert: unable to load module '/usr/local/Cellar/imagemagick/7.0.7-3/lib/ImageMagick//modules-Q16HDRI/coders/png.la': file not found @ error/module.c/OpenModule/1270.
convert: no encode delegate for this image format `XC' @ error/constitute.c/WriteImage/1167.

Highlighting colors with gutter icons is not supported with current ImageMagick setup. Try configuring the "icon_factory setting"
ColorHighlighter: action=highlight highlighter=ColorSchemeColorHighlighter region=(666, 673) color=#7c878eff
ColorHighlighter: action=highlight highlighter=ColorSchemeColorHighlighter region=(728, 732) color=#ffffffff
ColorHighlighter: action=highlight highlighter=ColorSchemeColorHighlighter region=(873, 880) color=#f0f2f4ff
ColorHighlighter: action=highlight highlighter=ColorSchemeColorHighlighter region=(1083, 1090) color=#4a4a4aff
ColorHighlighter: action=highlight highlighter=ColorSchemeColorHighlighter region=(1428, 1432) color=#ffffffff
ColorHighlighter: action=highlight highlighter=ColorSchemeColorHighlighter region=(2186, 2193) color=#e4e5e5ff
ColorHighlighter: action=highlight highlighter=ColorSchemeColorHighlighter region=(2398, 2402) color=#ffffffff
```

ImageMagick is installed via Homebrew, and the file exists and it's readable (-rwxr-xr-x). What about that double slash in the file path?

**Comment by glrodasz** [comment]
I'm having the same issue Sublime 3 just stopped working on Mac OS Sierra 10.12.6

```
Date/Time:       2017-10-05 22:20:01 -0500
OS Version:      Mac OS X 10.12.6 (Build 16G29)
Architecture:    x86_64h
Report Version:  25

Data Source:     Stackshots

Command:         Sublime Text
Path:            /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
Version:         Build 3143 (3143)
Parent:          launchd [1]
PID:             81872

Event:           hang
Duration:        6.60s (process was unresponsive for 8 seconds before sampling)
Steps:           66 (100ms sampling interval)

Hardware model:  MacBookPro11,5
Active cpus:     8

Fan speed:       2163 rpm

--------------------------------------------------
Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting
--------------------------------------------------

Heaviest stack for the main thread of the target process:
  66  start + 52 (Sublime Text + 7140) [0x1040c1be4]
  66  main + 3200 (Sublime Text + 11536) [0x1040c2d10]
  66  px_run_event_loop() + 190 (Sublime Text + 2719514) [0x104357f1a]
  66  -[NSApplication run] + 926 (AppKit + 242651) [0x7fffa077e3db]
  66  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796 (AppKit + 8136686) [0x7fffa0f057ee]
  66  _DPSNextEvent + 1120 (AppKit + 289364) [0x7fffa0789a54]
  66  _BlockUntilNextEventMatchingListInModeWithFilter + 71 (HIToolbox + 199462) [0x7fffa21f0b26]
  66  ReceiveNextEventCommon + 432 (HIToolbox + 199921) [0x7fffa21f0cf1]
  66  RunCurrentEventLoopInMode + 240 (HIToolbox + 200380) [0x7fffa21f0ebc]
  66  CFRunLoopRunSpecific + 420 (CoreFoundation + 553236) [0x7fffa2c90114]
  66  __CFRunLoopRun + 934 (CoreFoundation + 554774) [0x7fffa2c90716]
  66  __CFRunLoopDoSources0 + 557 (CoreFoundation + 557597) [0x7fffa2c9121d]
  66  __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17 (CoreFoundation + 684833) [0x7fffa2cb0321]
  66  __NSThreadPerformPerform + 326 (Foundation + 464170) [0x7fffa46f252a]
  66  ns_work_queue_runner::run_items() + 168 (Sublime Text + 2715156) [0x104356e14]
  66  handle_async_protocol_message(void*) + 52 (Sublime Text + 622654) [0x10415803e]
  66  handle_protocol_message(string_buffer const&) + 2035 (Sublime Text + 585347) [0x10414ee83]
  66  api_plugin_host_loaded_plugins() + 84 (Sublime Text + 583255) [0x10414e657]
  66  int send_helper<int>::send_message<3u>() + 205 (Sublime Text + 510081) [0x10413c881]
  66  void wait_for_reply<int>(reply_entry*, int*) + 161 (Sublime Text + 630997) [0x10415a0d5]
  66  shm_channel::read_message(string_buffer*, int) + 48 (Sublime Text + 2909942) [0x1043866f6]
  66  sem_wait + 10 (libsystem_kernel.dylib + 111486) [0x7fffb854837e]
 *66  hndl_unix_scall64 + 22 (kernel + 634262) [0xffffff800029ad96]
 *66  unix_syscall64 + 597 (kernel + 6439157) [0xffffff80008240f5]
 *66  sem_wait_nocancel + 171 (kernel + 6208043) [0xffffff80007eba2b]
 *66  ??? (kernel + 1107513) [0xffffff800030e639]
 *66  thread_block_reason + 222 (kernel + 1057470) [0xffffff80003022be]
 *66  ??? (kernel + 1062043) [0xffffff800030349b]
 *66  machine_switch_context + 206 (kernel + 2070942) [0xffffff80003f999e]
```

**Comment by DanielSmedegaardBuus** [comment]
@Monnoroch , I unlinked imagemagick, and then removed and re-installed Color Highlighter via Package Manager. Doing that, the plugin still worked just fine.

I thought that maybe some "good" configuration files were left behind in Sublime's Packages folder, so I uninstalled Color Highlighter again, and indeed there were some Cache and other files from your plugin left. I purged those folders and reinstalled the plugin, and am now again seeing the weird behavior with the colored blocks on lines below code.

Here's the log output (is there any other log I can get for you? I haven't logged Sublime Text before) from me installing the plugin:

```
>>> sublime.log_commands(True)
command: show_overlay {"overlay": "command_palette"}
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
Could not import subprocess32 module, falling back to subprocess module
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
command: install_package
ignored packages updated to: ["Color Highlighter", "Material Theme", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Material Theme", "Vintage"]
reloading plugin Color Highlighter.color_converter
reloading plugin Color Highlighter.color_highlighter
reloading plugin Color Highlighter.color_hover_listener
reloading plugin Color Highlighter.color_scheme
reloading plugin Color Highlighter.color_scheme_color_highlighter
reloading plugin Color Highlighter.color_searcher
reloading plugin Color Highlighter.color_selection_listener
reloading plugin Color Highlighter.colors
reloading plugin Color Highlighter.content_listener
reloading plugin Color Highlighter.convert_color_command
reloading plugin Color Highlighter.css_colors
reloading plugin Color Highlighter.dummy_event_listener
reloading plugin Color Highlighter.gutter_icons_color_highlighter
reloading plugin Color Highlighter.load_resource
reloading plugin Color Highlighter.main
Traceback: error.

Output:


Error:
/bin/sh: convert: command not found

Highlighting colors with gutter icons is not supported with current ImageMagick setup. Try configuring the "icon_factory setting"
reloading plugin Color Highlighter.path
reloading plugin Color Highlighter.phantoms_color_highlighter
reloading plugin Color Highlighter.pick_color_command
reloading plugin Color Highlighter.regex_compiler
reloading plugin Color Highlighter.regions
reloading plugin Color Highlighter.set_setting_command
reloading plugin Color Highlighter.settings
reloading plugin Color Highlighter.st_helper
reloading plugin Color Highlighter.topsort
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

It looks like maybe you're writing some configuration files upon install, but as imagemagick's `convert` binary is not found, something throws, and you're not catching it? Perhaps you're then ending up having written invalid configuration files? This would explain why it's not enough for me to install imagemagick to fix the problem — I have to uninstall, then reinstall the plugin as well (actually, this time around, I still have the weird colored blocks on their own extra lines, so I guess I'll have to purge my Sublime configurations folder again for plugin files).

I'm pretty sure you can replicate this if you uninstall the plugin, remove anything related to your plugin from the sublime config folder (`find [wherever-sublime-stores-the-conf-on-linux) -iname '*highlighter*'`), rename imagemagick's `convert` binary (`which convert`), and then reinstall the plugin. It should throw in main.

Hope this helps :) Let me know if I can provide any additional info!

**Comment by Monnoroch** [comment]
@DanielSmedegaardBuus it doesn't throw in main. The error in the log is a correctly handled error that doesn't impact the plugin's code in any way except for disabling gutter icons, of course. So if this is not a problem and the colored blocks are not a problem, what is?

**Comment by Monnoroch** [comment]
@lec00q #392.

**Comment by gonzaloquintas** [comment]
Hi!
I´m having the same issue as all here. There´s no way I can make CH work.
I´m on WIN10, ST 3143. Material Theme Darker, Color Scheme Monokai.

And this is the log: Error:
```
'utf-8' codec can't decode byte 0xa0 in position 3: invalid start byte
Highlighting colors with gutter icons is not supported with current ImageMagick setup. Try configuring the "icon_factory setting"
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2018-01-28 17:25:58, next run at 2018-01-28 18:25:58 or after
```
(ImageMagick is currently uninstalled, don´t know why I have that message)

I´ve installed, uninstalled the package, I installed and uninstalled ImageMagick, deleted folders, Changed themes and color schemes... I even reinstalled ST and nothing seems to fix this :S

The most weird of all is that after a clean reinstall of ST with all default values and only ColorHightlighter installed, it didn´t work either :/

Am I doing something wrong?

**Comment by Monnoroch** [comment]
@lordrott Three or more separate issues were discussed and solved here, so "same as all" doesn't mean anything, because everyone had different problems. If you have a problem, please create a new issue with detailed explanation.

**Comment by gonzaloquintas** [comment]
With "same as all", I meant that I´m here because the plugin isn´t working for me; not because the reasons of the plugin failure were the same.

Thanks anyway

**Comment by Monnoroch** [comment]
If you can describe the "not working" in more detail and provide additional logs with `"debug": true` setting enabled in plugin settings, I might be able to help with resolving the issue.

**Comment by ezeeyahoo** [comment]
```
startup, version: 3143 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/eshant/Library/Application Support/Sublime Text 3/Packages
state path: /Users/eshant/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/eshant/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Git", "GitSavvy", "RestructuredText", "SublimeLinter-flake8", "Vintage"]
pre session restore time: 0.320233
startup time: 0.405017
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Color Highlighter.color_converter
reloading plugin Color Highlighter.color_highlighter
reloading plugin Color Highlighter.color_hover_listener
reloading plugin Color Highlighter.color_scheme
reloading plugin Color Highlighter.color_scheme_color_highlighter
reloading plugin Color Highlighter.color_searcher
reloading plugin Color Highlighter.color_selection_listener
reloading plugin Color Highlighter.colors
reloading plugin Color Highlighter.content_listener
reloading plugin Color Highlighter.convert_color_command
reloading plugin Color Highlighter.css_colors
reloading plugin Color Highlighter.dummy_event_listener
reloading plugin Color Highlighter.gutter_icons_color_highlighter
reloading plugin Color Highlighter.load_resource
reloading plugin Color Highlighter.main
reloading plugin Color Highlighter.path
reloading plugin Color Highlighter.phantoms_color_highlighter
reloading plugin Color Highlighter.pick_color_command
reloading plugin Color Highlighter.regex_compiler
reloading plugin Color Highlighter.regions
reloading plugin Color Highlighter.set_setting_command
reloading plugin Color Highlighter.settings
reloading plugin Color Highlighter.st_helper
reloading plugin Color Highlighter.topsort
reloading plugin Emmet.emmet-plugin
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Python Imports Sorter.__init__
reloading plugin Python Imports Sorter.organizer
reloading plugin Python Imports Sorter.python_imports_sorter
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
ColorHighlighter: action=start st=st3
ColorHighlighter: action=create_icon style=circle color=#ffffffff
Traceback: error.

Output:


Error:
/bin/sh: convert: command not found

Highlighting colors with gutter icons is not supported with current ImageMagick setup. Try configuring the "icon_factory setting"
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2018-02-24 17:57:48, next run at 2018-02-24 18:57:48 or after
environment variables loaded using: /bin/zsh -l

```

**Comment by lufog** [comment]
DPI mode: per-monitor v2
startup, version: 3176 windows x64 channel: stable
executable: /D/Program Files/Portable/Sublime Text/sublime_text.exe
working dir: /D/Program Files/Portable/Sublime Text
packages path: /D/Program Files/Portable/Sublime Text/Data/Packages
state path: /D/Program Files/Portable/Sublime Text/Data/Local
zip path: /D/Program Files/Portable/Sublime Text/Packages
zip path: /D/Program Files/Portable/Sublime Text/Data/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.225325
startup time: 0.329325
first paint time: 0.331325
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Color Highlighter.color_converter
reloading plugin Color Highlighter.color_highlighter
reloading plugin Color Highlighter.color_hover_listener
reloading plugin Color Highlighter.color_scheme
reloading plugin Color Highlighter.color_scheme_color_highlighter
reloading plugin Color Highlighter.color_searcher
reloading plugin Color Highlighter.color_selection_listener
reloading plugin Color Highlighter.colors
reloading plugin Color Highlighter.content_listener
reloading plugin Color Highlighter.convert_color_command
reloading plugin Color Highlighter.css_colors
reloading plugin Color Highlighter.dummy_event_listener
reloading plugin Color Highlighter.gutter_icons_color_highlighter
reloading plugin Color Highlighter.load_resource
reloading plugin Color Highlighter.main
reloading plugin Color Highlighter.path
reloading plugin Color Highlighter.phantoms_color_highlighter
reloading plugin Color Highlighter.pick_color_command
reloading plugin Color Highlighter.regex_compiler
reloading plugin Color Highlighter.regions
reloading plugin Color Highlighter.set_setting_command
reloading plugin Color Highlighter.settings
reloading plugin Color Highlighter.st_helper
reloading plugin Color Highlighter.topsort
reloading plugin Emmet.emmet-plugin
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
ColorHighlighter: action=start st=st3
ColorHighlighter: action=create_icon style=circle color=#ffffffff
Traceback: error.

Output:


Error:
'utf-8' codec can't decode byte 0x8d in position 0: invalid start byte
Highlighting colors with gutter icons is not supported with current ImageMagick setup. Try configuring the "icon_factory setting"
Traceback (most recent call last):
  File "D:\Program Files\Portable\Sublime Text\sublime_plugin.py", line 283, in on_api_ready
    m.plugin_loaded()
  File "D:\Program Files\Portable\Sublime Text\Data\Installed Packages\Color Highlighter.sublime-package\main.py", line 606, in plugin_loaded
    ColorHighlighterPlugin.init()
  File "D:\Program Files\Portable\Sublime Text\Data\Installed Packages\Color Highlighter.sublime-package\main.py", line 319, in init
    ColorHighlighterPlugin._fake_color_scheme = ColorHighlighterPlugin.components.provide_fake_color_scheme()
  File "D:\Program Files\Portable\Sublime Text\Data\Installed Packages\Color Highlighter.sublime-package\main.py", line 197, in provide_fake_color_scheme
    return self.provide_fake_color_scheme_data()[0]
  File "D:\Program Files\Portable\Sublime Text\Data\Installed Packages\Color Highlighter.sublime-package\main.py", line 188, in provide_fake_color_scheme_data
    self._fake_color_scheme_data = parse_color_scheme(self.provide_color_scheme(), self._settings.debug)
  File "D:\Program Files\Portable\Sublime Text\Data\Installed Packages\Color Highlighter.sublime-package\color_scheme.py", line 40, in parse_color_scheme
    color_scheme_content = load_resource.load_resource(color_scheme)
  File "D:\Program Files\Portable\Sublime Text\Data\Installed Packages\Color Highlighter.sublime-package\load_resource.py", line 30, in load_resource
    return sublime.load_resource(file_path)
  File "D:\Program Files\Portable\Sublime Text\sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2018-05-28 18:01:06, next run at 2018-05-28 19:01:06 or after
