### ISSUE TITLE
Background color for Text option

### ISSUE THREAD

**Issue by kanjigirl** [Monnoroch/ColorHighlighter#382]
How can I remove the dark background fill if I use the Text inline highlighting style?  Some colors of text just disappear against the background.

![colors](https://user-images.githubusercontent.com/601367/31204340-b0193668-a928-11e7-9c53-a2d46c8cb4e1.jpg)

**Comment by kanjigirl** [comment]
Sorry - I'm using Mustard with the Colorsublime-Themes package - not sure how to attach it...

**Comment by Monnoroch** [comment]
@kanjigirl I'm going to need instructions on how to install your color scheme, didn't find in on PC.

**Comment by kanjigirl** [comment]
Here's the source info on Colorsublime-Themes:

https://github.com/Colorsublime/Colorsublime-Themes

But really it's not that important, using the color fill inline highlighting works okay. It was just an abrupt change from what I was used to seeing.

**Comment by Monnoroch** [comment]
Well, not quite, the screenshot shows something strange.

**Comment by kanjigirl** [comment]
The screenshot is the Text highlighting. When I switch to Fill, it's fine and shows correctly.

**Comment by Monnoroch** [comment]
Well, then there's a bug in the text highlighting :) I'll look into it later.

**Comment by kanjigirl** [comment]
Thanks!

**Comment by leem32** [comment]
I also have this issue using the 'Flatland Black,' color scheme.

**Comment by Monnoroch** [comment]
I've tested the Mustard theme and it works perfectly for me. Can't reproduce the problem.
