### ISSUE TITLE
Issues with new sublime text3.0 build 3143 Win 10

### ISSUE THREAD

**Issue by hoanganhpocolo** [Monnoroch/ColorHighlighter#385]
![image](https://user-images.githubusercontent.com/27997243/31224455-2f55bc74-a9f8-11e7-91f5-b60b2d5967b1.png)

**Comment by Monnoroch** [comment]
Logs?

**Comment by hoanganhpocolo** [comment]
Sry. it's only  a bit strange on new UI,  i get used to older UI of ColorHighlighter. 
It is not an issues. U can close it. 
Sry about that.

**Comment by Monnoroch** [comment]
You can configure the plugin to be just like it was before if you prefer.
