### ISSUE TITLE
All colors is purple and on click its push next line down omg

### ISSUE THREAD

**Issue by weltkind-dmitry-savinkov** [Monnoroch/ColorHighlighter#386]
Screenshot of that: http://prntscr.com/gtxo4t

**Comment by leem32** [comment]
Try turning off 'highlight colors with blocks' in the options menu for all 3 subsections.
Tools > Color Highlighter > Color Highlighters

**Comment by weltkind-dmitry-savinkov** [comment]
Oh thanks. I'm also set 'highlight colors in all text -> Inline highlighted style' to 'filled'. Very thanks)

**Comment by Monnoroch** [comment]
@weltkind-dmitry-savinkov what is your ST version and a color scheme where this breakes?

**Comment by Monnoroch** [comment]
Moved it here: #391.
