### ISSUE TITLE
How to turn off that shudder of lines when color is clicked CSS files?

### ISSUE THREAD

**Issue by wzup** [Monnoroch/ColorHighlighter#389]
How to turn off that annoying effect? When a color is clicked or selected a line suddenly unfolds and turns into two lines? 
Why drop color below the line? Why not to display it on the right to the comma? In one line. Not two. 

Normal state:

![colors unfold scss - sublime text unregistered 2017-10-06 22 19 19](https://user-images.githubusercontent.com/3880497/31282228-78d7df52-aae4-11e7-8d8d-804d4520307a.png)

Unfolded state:

![colors unfold scss - sublime text unregistered 2017-10-06 22 17 46](https://user-images.githubusercontent.com/3880497/31282239-84a7af6a-aae4-11e7-978e-5a7e929c5608.png)

**Comment by Monnoroch** [comment]
It is explained in the readme.

**Comment by wzup** [comment]
@Monnoroch 

It is obviously a convenient to see a color in block. But why drop a color below the line? Why not to display it on the right to the comma? On the same line. It wouldn't irritate eyesight.  Every time brain doesn't understand what happens.

**Comment by Monnoroch** [comment]
This is a good idea indeed, thanks!

**Comment by Monnoroch** [comment]
#390

**Comment by Monnoroch** [comment]
@wzup I've implemented what you asked for in `8.0.8`. Please check it out, I will be waiting for the feedback!
