### ISSUE TITLE
ColorHighlighter is installed, but won't works

### ISSUE THREAD

**Issue by Tom250** [Monnoroch/ColorHighlighter#394]
Hey,

I'm new into Sublime Text 3, and changed not early from Notepad++.
I need an previewer to show me the Hex Colors, but this happens:
https://image.prntscr.com/image/Fq3vKww9TjKNUV-i30v3eA.png
And the proof that it is installed:
https://image.prntscr.com/image/xWvAi8F3RSS4qXRHTPgEIQ.png

Thanks!

**Comment by Monnoroch** [comment]
Duplicates #381.

**Comment by Tom250** [comment]
I don't think that it don't duplicates it. If yes, please tell me why. I can't understand it.

**Comment by Monnoroch** [comment]
Your issue is about named color not being highlighted. The issue iI linked is about supporting named colors.
