### ISSUE TITLE
Highlighter Coloring Text, not underlining

### ISSUE THREAD

**Issue by thenoelforte** [Monnoroch/ColorHighlighter#397]
I've run across what appears to be a bug in the most recent version of ColorHighlighter. Rather than underlining the colors, the text itself being set in the color defined. Upon placing the cursor in the color code, a box containing the color appears to the right of the code.

<img width="306" alt="screen shot 2017-10-13 at 3 05 24 pm" src="https://user-images.githubusercontent.com/2560683/31562115-3bb04198-b028-11e7-809e-cff352df5942.PNG">

Sublime Version: `Version 3.0, Build 3143`
Operating System: `macOS 10.13`

**Comment by Monnoroch** [comment]
Please read the readme to find out all the options.

**Comment by thenoelforte** [comment]
aw shoot, sorry about that. thanks.
