### ISSUE TITLE
Color conversion from Hex to RGB is incorrect

### ISSUE THREAD

**Issue by gerardroche** [Monnoroch/ColorHighlighter#402]
I could very well be misunderstanding color conversion.

# Test `#1d2021`

Converting `#1d2021` (`Ctrl+Shift+,`) we get (on each conversion):

```
#1d2021
#1d2021ff
hsl(195, 6%, 12%)
hsla(180, 5%, 12%, 1.)
hsv(180, 9%, 13%)
hsva(180, 9%, 13%, 1.)
rgb(30, 33, 33)
```

## Actual

`rgb(30, 33, 33)`

## Expected 

`rgb(29, 32, 33)`

# Test `#282828`

## Actual

`rgb(41, 41, 41)`

## Expected

`rgb(40, 40, 40)`

**Comment by Monnoroch** [comment]
These problems are probably due to rounding issues you have when converting RGBA to hsl and back. Not sure how to avoid those.

**Comment by gerardroche** [comment]
The conversion is kind of misleading. You expect the rgb to be from the original conversion. 

One thing you could do is keep a history of conversions. Where a user presses the conversion six times, as I did, they should all convert from the first converted value.

It's probably still error prone as the user expectations is that there is no data loss on conversion.

Another alternative is prompt with select list of what to convert to and change the conversion cycle keybinding to only cycle through conversions that have no data loss.

**Comment by Monnoroch** [comment]
> there is no data loss on conversion

Well, that is just impossible.

The other solutions are quite awkward too. I thinks is just has to be accepted that there's data loss on conversion.

**Comment by gerardroche** [comment]
I don't understand that it's impossible. `#282828` converts to `rgb(40, 40, 40)` and vice-versa?

**Comment by Monnoroch** [comment]
I'm talking about hsl conversion. It will always be lossy. A select list is probably the best way to solve this indeed.

**Comment by gerardroche** [comment]
How many conversions have no data loss? RGB and HEX have no data loss. The problem with cycling though the conversions for color idiots like me is that I don't know which ones have data loss so I'd prefer to only cycle though ones that have no data loss. 

There could be two cycle commands: one that cycles though only those that have no data loss and one that cycle though them all. The default should be to only cycle to non lossy conversions. For dummies like me.

**Comment by Monnoroch** [comment]
I don't know. I do agree that there's a problem, but having two commands is just way too complicated. And only looping through lossless conversions is also not intuitive to me. My favorite solution is to not change this command and to have the context-menu command that provides a list with "lossy" marks.
