### ISSUE TITLE
Error: 'utf-8' codec can't decode byte 0x83 in position 3: invalid start byte

### ISSUE THREAD

**Issue by PedroAF21** [Monnoroch/ColorHighlighter#410]
Color Highlighter is not working properly, it's not displaying the colors at all.
I got this error message.
Error:
'utf-8' codec can't decode byte 0x83 in position 3: invalid start byte
Highlighting colors with gutter icons is not supported with current ImageMagick setup. Try configuring the "icon_factory setting"
Unable to open /C/Users/T-Gamer/AppData/Roaming/Sublime Text 3/Packages/Color Highlighter/ColorHighlighter.sublime-settings

Windows 10 
Sublime Text 3 Build 3143

**Comment by Monnoroch** [comment]
Well, there's you answer. The ColorHighlighter.sublime-settings can't be opened.
