### ISSUE TITLE
Solution for the "ImageMagick" path contains [Space]

### ISSUE THREAD

**Issue by APSlee** [Monnoroch/ColorHighlighter#411]
U Must install the right version of ImageMagick and set the path right in the plugin setting to make the gutter color icon work.
I used to have a problem about the gutter color. Turned out, it is caused by two reason.
1.Version:  if you install the latest version of this plugin, U should install ImageMagick 7.0.0+ and later.
2.Path: if Ur path of the `"ImageMagick->convert"` contains [Space], and U set `"icon_factory"->"convert_path"` like this: 
`"convert_command":` "D:/Program Files/ImageMagick-7.0.7-8-portable-Q16-x86/convert.exe",
It won't work at least on Windows system. Instead, U should set it like this:
`"convert_command":` "D:/\"Program Files\"/ImageMagick-7.0.7-8-portable-Q16-x86/convert.exe",

Hope it will be helpful.

**Comment by Monnoroch** [comment]
This is how paths work on windows. Not sure what to do about it.
