### ISSUE TITLE
Regex question

### ISSUE THREAD

**Issue by Resike** [Monnoroch/ColorHighlighter#413]
Could the regex handling changed like this? Match the whole regex, but only color whats inside the first parentheses.

`"regex": "#([0-9a-fA-F]{8})",`

**Comment by Resike** [comment]
Like supporting something like that would be super cool:

` "sharp3": {
                "description": "Hex #RGB color format",
                "regex": "#(?P<H>highlight(?P<R>hex)(?P<G>hex)(?P<B>hex))",
                "white": "#FFF",
                "after": "sharp4"
            },`

Then only color the H part.

**Comment by Monnoroch** [comment]
It's possible, but I don't really understand why would you do that.

**Comment by Resike** [comment]
I made a modified version and it works/would work like this:
https://www.youtube.com/watch?v=5rpsGn-L960

**Comment by Monnoroch** [comment]
Well alright, but I see no point doing that.
