### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Resike** [Monnoroch/ColorHighlighter#414]
Using the _Tools->Color Highlighter->Color highlighters->Highlight colors in all text-> **any of the** Highlight colors with block_ settings **_but None_** throws an error and brakes the functionality of the package until you reset the settings for the package.

**Comment by Monnoroch** [comment]
I need logs to help you with your problem.

**Comment by Resike** [comment]
You should be able to reproduce it on a fresh settings fresh install.

2017-11-03 20:38 GMT+01:00 Max <notifications@github.com>:

**Comment by Monnoroch** [comment]
I don't, so I need the logs, your OS and ST versions.

**Comment by Resike** [comment]
ST3 Build 3143, WIndows 7 x64 6.1 build 7601

**Comment by Cutepally** [comment]
i also had this error

**Comment by msantoro12** [comment]
Same osx 10.11.6 sublime Dev Channel, Build 3153. This is one of my favorite plugin! I will give you money.

**Comment by Monnoroch** [comment]
Guys, I can't support dev builds. The are called dev builds precicely because they might break things.

**Comment by Resike** [comment]
Mine is on the latest stable release.

**Comment by Monnoroch** [comment]
The original problem is because of broken settings file. Please fix it and it will go away. I'm adding better error messages right now.

**Comment by Resike** [comment]
I know that caused because the settings are broken. But the settings gets broken when you click on the "Show color at the right side of the text".

**Comment by Resike** [comment]
Here is a video about how to actually trigger the issue, stock fresh install Sublime, latest stable release, default package settings:
https://www.youtube.com/watch?v=FAb7LSDNbDs

**Comment by Monnoroch** [comment]
Video not available.

**Comment by Monnoroch** [comment]
@Resike fixed it anyway :)

**Comment by Resike** [comment]
Thanks, i also dug into it now and found the issue myself too. But i was right you see. :P

**Comment by GoMrPickles** [comment]
"The original problem is because of broken settings file. Please fix it and it will go away."
I will, but - which settings file, and how does one fix it? I am experiencing this error, per: https://github.com/Monnoroch/ColorHighlighter/issues/436
