### ISSUE TITLE
Automatically detect changes on the Color Scheme file

### ISSUE THREAD

**Issue by evandrocoan** [Monnoroch/ColorHighlighter#422]
When editing the color scheme and using Color Highlighter, you cannot see the changes until you restart Sublime Text, which is bad. But ColorHighlighter should listen for changes on the user default ColorScheme and update itself automatically, instead of force the user to restart Sublime Text to the changes take effect.

**Comment by Monnoroch** [comment]
Editing a color scheme is a too specific problem. What you want would require significant performance penalty for all scenarios. So until there isn't a way to do it efficiently this is not worth implementing.

**Comment by evandrocoan** [comment]
Would it not just required to setup a watchdog on the original use color scheme file, with a callback to this package function which updates it?

**Comment by Monnoroch** [comment]
If you have a way to do it efficiently on all platforms, please send a PR :)
