### ISSUE TITLE
insert color when clicking on block

### ISSUE THREAD

**Issue by AmjadHD** [Monnoroch/ColorHighlighter#424]
It'll be handy to open the color picker when clicking on the color block next to the color

![color](https://user-images.githubusercontent.com/33235928/33663874-de2c9974-da91-11e7-91db-36302873d5ad.png)

Hope you consider it!

**Comment by Monnoroch** [comment]
There's a hotkey for it, so I don't see much benefit. Clicking on it accidentally would also be a UX problem. Probably not worth implementing.
