### ISSUE TITLE
Bug "inline"

### ISSUE THREAD

**Issue by emkei-cz** [Monnoroch/ColorHighlighter#427]
Hi,
Instead of "inline" there should be "right"
but through the "Tools" setting I always get "inline" that does not work

`		"all_content":
		{
			"color_highlighters":
			{
				"color_scheme":
				{
					"enabled": false,
					"highlight_style": "text"
				},
				"gutter_icons":
				{
					"enabled": false,
					"icon_style": "circle"
				},
				"phantoms":
				{
					"enabled": true,
					"length": 2,
					"style": "inline"
				}`

**Comment by Monnoroch** [comment]
Already fixed yesterday.
