### ISSUE TITLE
Can't working on my sublime 3 version: 3059

### ISSUE THREAD

**Issue by fenbox** [Monnoroch/ColorHighlighter#46]
sublime 3 version: 3059, installed by Package Control, the menu was disabled:

![2014-03-21 2 29 13](https://f.cloud.github.com/assets/360618/2480570/2e8da258-b0c2-11e3-86fd-e057a3f93134.png)
### sublime console show errors:

```
File "ColorHighlighter in /Users/fen/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 10, in <module>
ImportError: No module named 'ColorHighlighter'
```

**Comment by elfassy** [comment]
I had a similar problem and changing the folder name from `ColorHighlighter-master` to `Color Highlighter` did the trick for me
